import { allowExpectedDiagnostic, expect, openSamples, switchWorkspace, test } from "./journey.js";
import { readFileSync } from "node:fs";

// A TEST THAT REFUSES TO PASS IF THE OVERLAY BUDGET WAS NEVER EVALUATED.
//
// `auto: true`, so the guard runs because the test RAN -- not because its body mentions the fixture,
// and not because a rule read the body looking for a call. Commenting the call out, wrapping it in
// `if (false)`, a body-level `test.skip()` and deleting the call all leave the counter unmoved and
// are refused identically; none of them is a spelling this has to know about in advance.
//
// IT CANNOT CATCH THE `.skip` / `.fixme` MODIFIERS, and saying so is the point. Playwright suppresses
// a modified test BEFORE fixture setup, so this fixture never runs at all -- an earlier revision of
// this comment claimed skipping was "refused identically", which was true of the body-level form and
// false of the modifier, and that one sentence hid a real escape. The modifiers are refused by the
// run-level net instead, keyed off the tag below.
//
// Scoped to this one test rather than the file, deliberately. CI shards this suite, so a file-level
// hook would refuse every shard that does not carry this test -- a gate that reds on correct runs is
// a gate that gets removed. And a `test.describe` wrapper would change the test's reported name,
// which readiness/183-tactical-overlays/*.junit.xml pins.
const guardedBudgetTest = test.extend({
  overlayBudgetEvaluated: [async ({}, use) => {
    const mark = tacticalOverlayLayerEvaluationMark();
    await use();
    assertTacticalOverlayLayerBudgetWasEvaluatedSince(mark);
  }, { auto: true }],
});

// THE TAG IS BAKED IN, NOT WRITTEN AT THE DECLARATION. The run-level refusal keys off the tag, so a
// test that lost it would silently stop being covered by that net -- and a check that looked for the
// tag by searching this file was satisfied by the IMPORT line alone, which is the same
// narrower-than-its-claim shape this item keeps producing. Injecting it here means there is one
// thing to remove rather than two.
const overlayBudgetTest = (title, body) => guardedBudgetTest(title, { tag: tacticalOverlayLayerBudgetTag }, body);

// AND THE SUPPRESSION MODIFIERS ARE REFUSED BY NAME. Playwright applies `.skip` / `.fixme` before
// fixture setup, so nothing belonging to the test can object -- one token turned a real breach into
// `1 skipped`, exit 0, `failures="0"`. A plain function has no such properties, so they would already
// fail; defining them makes the failure say WHY instead of reading like a broken harness.
for (const modifier of ["skip", "fixme", "only"])
  overlayBudgetTest[modifier] = () => {
    throw new Error(`this test carries ${tacticalOverlayLayerBudgetTag} and cannot be suppressed with .${modifier}: the overlay-layer node budget is enforced only by running it, and Playwright applies that modifier before any guard belonging to the test can object. Remove the budget obligation deliberately, or fix what is failing.`);
  };
import { assertTacticalOverlayLayerBudget, assertTacticalOverlayLayerBudgetWasEvaluatedSince, tacticalFrameBudget, tacticalOverlayLayerBudgetTag, tacticalOverlayLayerEvaluationMark, tacticalWorkloadBudgetAtScale } from "../../scripts/lib/performance-budget.mjs";

// Generated by the canonical SIR.Simulation.Replay encoder from the retained
// PerspectivePlayback package used by SIR.Client.Tests; the engine hash is
// intentionally embedded so a changed engine rejects this fixture.
const retainedReplay = Buffer.from(
  readFileSync(new URL("../fixtures/retained-perspective-replay.sirr.base64", import.meta.url), "utf8").trim(),
  "base64",
);
const rulesImplementationSources = JSON.parse(
  readFileSync(new URL("../fixtures/rules-corpus/v2/implementation-sources.json", import.meta.url), "utf8"),
);

async function loadMaintainedSimulation(page) {
  await page.goto("/");
  await switchWorkspace(page, "Simulate");
  await openSamples(page);
  const samplesOwner = page.getByLabel("Curated samples feature", { exact: true });
  await expect(samplesOwner).toBeVisible();
  await expect(samplesOwner.getByRole("region", { name: "Curated maps simulations and replays", exact: true })).toBeVisible();
  await samplesOwner.getByText("Troll assault", { exact: true }).click();
  await samplesOwner.getByRole("button", { name: "Run Troll assault in Simulator", exact: true }).click();
}

async function expandPanel(page, panelId) {
  const panel = page.locator(`[data-panel-id="${panelId}"]`);
  if (await panel.count() === 0) {
    await page.locator("details.tactical-panel-menu").click();
    await page.locator(`#layout-show-${panelId}`).click();
  }
  if (await panel.getAttribute("data-collapsed") === "true" || await panel.evaluate((node) => node.classList.contains("is-collapsed"))) {
    await panel.locator(`#layout-panel-${panelId}-collapse`).click();
  }
  await expect(panel).toBeVisible();
  return panel;
}

async function observableUnitState(battlefield, unitIds = null) {
  return battlefield.locator("#persistent-layer-units [data-unit-id]").evaluateAll((units, retainedIds) =>
    units
      .filter((unit) => retainedIds === null || retainedIds.includes(unit.getAttribute("data-unit-id")))
      .map((unit) => ({
        id: unit.getAttribute("data-unit-id"),
        classId: unit.getAttribute("data-unit-class"),
        footprint: unit.getAttribute("data-unit-footprint"),
        status: unit.getAttribute("data-unit-status"),
        stance: unit.getAttribute("data-unit-stance"),
        column: unit.getAttribute("data-presentation-column"),
        row: unit.getAttribute("data-presentation-row"),
        // Capture the complete rendered runtime payload: glyph, label, health,
        // status markers, and direction geometry.
        rendered: unit.innerHTML,
        headings: [...unit.querySelectorAll("[data-unit-heading]")].map((heading) => ({
          kind: heading.getAttribute("data-unit-heading"),
          x1: heading.getAttribute("x1"),
          y1: heading.getAttribute("y1"),
          x2: heading.getAttribute("x2"),
          y2: heading.getAttribute("y2"),
        })),
      }))
      .sort((left, right) => Number(left.id) - Number(right.id)),
    unitIds,
  );
}

// Diagnostics-gate self-tests deliberately issue a browser fetch; they are not product-journey evidence.
test("explicitly allowed rejection diagnostics do not hide unrelated browser failures", async ({ page }) => {
  await page.route("**/controlled-rejection", (route) => route.fulfill({ status: 418, body: "expected" }));
  allowExpectedDiagnostic(page, /controlled-rejection|I'm a teapot/);
  await page.goto("/");
  await page.evaluate(() => fetch("/controlled-rejection"));
});

test("unexpected rejection diagnostics fail the journey gate", async ({ page }) => {
  test.skip(process.env.SIR_DIAGNOSTIC_SELF_TEST !== "1", "diagnostic gate child-process self-test only");
  await page.route("**/unexpected-rejection", (route) => route.fulfill({ status: 418, body: "unexpected" }));
  // Isolate the network threshold: Chromium emits a generic 418 console message
  // for fetch, while this child specifically proves the unallowlisted response gate.
  allowExpectedDiagnostic(page, /I'm a teapot/);
  await page.goto("/");
  await page.evaluate(() => fetch("/unexpected-rejection"));
});

test("visible View commands preserve a usable tactical workspace across authoring modes", async ({ page }) => {
  await page.goto("/");
  const workspace = page.getByRole("main", { name: "S.I.R. simulator and editor" });
  await expect(workspace).toBeVisible();

  for (const mode of ["Editor", "Plan", "Simulate", "Review"]) {
    await switchWorkspace(page, mode);
    await expect(workspace.getByRole("application")).toBeVisible();
  }
});

test("the production tactical visual system preserves causal feedback under reduced motion", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  await expect(battlefield).toHaveAttribute("data-visual-system", "tactical-visual-system-v1");
  await expect(battlefield).toHaveAttribute("data-motion", "reduced");
  await expect(battlefield).toHaveAttribute(
    "data-layer-order",
    "terrain>edges>routes>units>effects>selection>tactical-overlays>annotations",
  );
  const paintedOrder = await battlefield.locator("#persistent-scene-camera").evaluate((camera) =>
    [...camera.children].map((node) => node.getAttribute("data-scene-layer")).filter(Boolean).join(">"),
  );
  expect(paintedOrder).toBe(await battlefield.getAttribute("data-layer-order"));
  await expect(battlefield.locator("#persistent-layer-effects")).toHaveAttribute("data-effect-motion", "emphasis-120ms");

  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  const effectCount = Number(await battlefield.getAttribute("data-effect-count"));
  const effectLimit = Number(await battlefield.getAttribute("data-effect-limit"));
  const unitCount = Number(await battlefield.getAttribute("data-visual-unit-count"));
  const nodeEstimate = Number(await battlefield.getAttribute("data-visual-node-estimate"));
  expect(effectCount).toBeGreaterThan(0);
  // data-effect-limit is what the product ACTUALLY enforces (TacticalSceneProjection
  // .MaximumEffectInstances), read off the live DOM rather than restated here. This assertion was
  // already deriving before S.I.R.#318 and is deliberately left alone: turning it into a literal
  // would add a copy, not remove one. The declaration is bound to that runtime cap by a gate in
  // scripts/test-svg-pipeline-measurement.mjs.
  expect(effectCount).toBeLessThanOrEqual(effectLimit);
  expect(unitCount).toBeGreaterThan(0);
  // The node cap was a bare two-tier ternary over the two published caps -- the third independent
  // statement of the table's node column (S.I.R.#318). It is now DERIVED from the single declaration,
  // and the tier boundary is the declared workload's own unit count rather than a literal repeated
  // here. No number appears in this assertion, deliberately: a comment carrying one is a copy too.
  expect(nodeEstimate).toBeLessThanOrEqual(tacticalWorkloadBudgetAtScale(unitCount).maximumDomNodes);
  const firstEffect = battlefield.locator("#persistent-layer-effects [data-effect-event]").first();
  await expect(firstEffect).toHaveAttribute("data-effect-kind", /movement|attack|impact|suppression|recovery|signal|objective|event/);
  await expect(firstEffect).toHaveAttribute("data-effect-lifecycle", /preview|predicted|accepted|committed|rejected|historical/);
  expect(await firstEffect.evaluate((node) => getComputedStyle(node).animationDuration)).toBe("0.12s");
  await expect(battlefield.locator("#persistent-layer-effects")).toHaveAttribute("pointer-events", "none");
  await expect(battlefield.locator("#persistent-layer-units [data-unit-id]").first()).toBeVisible();

  const samples = await battlefield.evaluate(async (root) => {
    const values = [];
    for (let index = 0; index < 24; index += 1) {
      await new Promise((resolve) => requestAnimationFrame(() => {
        const started = performance.now();
        root.querySelectorAll("[data-unit-id], [data-effect-event], [data-overlay-id]").length;
        values.push(performance.now() - started);
        resolve();
      }));
    }
    return values.sort((left, right) => left - right);
  });
  // The ceiling is DERIVED from the single declaration (S.I.R.#299), not restated here. This gate
  // and the Chromium pipeline harness measure the same quantity, so they must read the same number.
  expect(samples[Math.floor(samples.length * 0.95)]).toBeLessThan(tacticalFrameBudget.callbackMillisecondsCeiling);
});

overlayBudgetTest("View analysis overlays share pointer and keyboard commands and restore independently", async ({ page }) => {
  await page.goto("/");
  const battlefield = page.locator("#persistent-tactical-svg");
  await expect(battlefield).toHaveAttribute("data-overlay-registry-traversals", "1");
  await expect(battlefield).toHaveAttribute("data-overlay-disclosure-passes", "1");

  await page.getByRole("button", { name: "View", exact: true }).click();
  const exactLos = page.getByRole("menuitemcheckbox", { name: /Exact line of sight/ });
  await expect(exactLos).toHaveAttribute("aria-checked", "false");
  await exactLos.dispatchEvent("pointerdown", { pointerId: 7, pointerType: "mouse", isPrimary: true });
  await expect(exactLos).toHaveAttribute("aria-checked", "true");
  await expect(exactLos).toHaveAttribute("data-overlay-mode", "InspectHeld");
  await exactLos.dispatchEvent("pointerup", { pointerId: 7, pointerType: "mouse", isPrimary: true });
  await expect(exactLos).toHaveAttribute("aria-checked", "false");
  await exactLos.click();
  await expect(battlefield).toHaveAttribute("data-overlay-preferences", /spatial\.exact-los=selection/);

  await page.reload();
  await expect(battlefield).toHaveAttribute("data-overlay-preferences", /spatial\.exact-los=selection/);
  await page.keyboard.press("Alt+l");
  await expect(battlefield).toHaveAttribute("data-overlay-preferences", /spatial\.exact-los=off/);

  const footprint = battlefield.locator('[data-overlay-id="unit.footprints"] rect').first();
  await expect(footprint).toBeVisible();
  await expect(footprint).toHaveCSS("vector-effect", "non-scaling-stroke");
  const normalStroke = await footprint.evaluate((node) => getComputedStyle(node).strokeWidth);
  expect(normalStroke).toBe("2px");
  await page.emulateMedia({ forcedColors: "active" });
  await expect.poll(() => footprint.evaluate((node) => getComputedStyle(node).strokeWidth)).toBe("3px");
  await page.evaluate(() => { document.documentElement.style.zoom = "4"; });
  await page.getByRole("button", { name: "View", exact: true }).click();
  await expect(page.getByRole("menuitemcheckbox", { name: /Unit footprints/ })).toBeVisible();
  const overlayLayer = battlefield.locator("#persistent-tactical-overlay-layer");
  // The overlay-layer node bound was a bare literal here -- the ONLY statement of it anywhere,
  // declared in no budget document, gating this browser test and nothing else (S.I.R.#327).
  //
  // The comparison is now something this spec CALLS rather than something it writes. The declaration
  // owns the bound, the telemetry cross-check against an independent count, and the order the two are
  // applied in; each is inverted in-process by scripts/test-svg-pipeline-measurement.mjs, which is
  // where this test cannot be. So there is no number here to restate and no comparison here to get
  // wrong -- and the cross-check cannot be dropped from this call site, because it is not written at
  // this call site.
  await assertTacticalOverlayLayerBudget(page);
  const footprintBox = await footprint.boundingBox();
  expect(footprintBox?.width).toBeGreaterThan(20);
  expect(footprintBox?.height).toBeGreaterThan(20);
  await expect(overlayLayer).toHaveAttribute("data-overlay-patterns", "non-color-only");
});

test("the player-visible Rules explorer renders the executable combat corpus and pinned source", async ({ page }) => {
  let physicalAuthorityRequests = 0;
  page.on("request", (request) => {
    if (request.url().includes("/api/combat/physical-drill")) physicalAuthorityRequests += 1;
  });
  await page.goto("/");
  await page.getByRole("button", { name: "View", exact: true }).click();
  await page.getByRole("menuitem", { name: /Rules data/ }).click();
  const explorer = page.getByRole("region", { name: "Rules data tables", exact: true });
  await expect(explorer).toBeVisible();
  await expect(explorer.getByRole("heading", { name: /FS\.GG\.Game\.Core@0\.13\.0/ })).toBeVisible();
  await expect(explorer.getByRole("heading", { name: /AttackResolved event/ })).toHaveCount(0);
  await explorer.getByRole("button", { name: "Execute canonical player attack" }).click();
  await expect(explorer.getByRole("heading", { name: "AttackResolved event tick-1-attack-10-20" })).toBeVisible();
  await expect(explorer.getByText(/Damage 25 · remaining health 75/)).toBeVisible();
  await expect(explorer.getByText(/COMBAT-DAMAGE-001.*baseDamage=.*trace=.*retention=.*→.*damage/)).toBeVisible();
  await explorer.getByRole("link", { name: "Open governing rule COMBAT-ATTACK-RESOLUTION-001" }).click();
  await expect(page).toHaveURL(/#rule-COMBAT-ATTACK-RESOLUTION-001$/);
  await expect(explorer.getByText("Transition · AttackPhase · events AttackResolved, CoverDestroyed", { exact: true })).toBeVisible();
  const damage = explorer.getByText(/^COMBAT-DAMAGE-001 · Expected damage$/);
  await damage.click();
  const damageRule = damage.locator("..");
  await expect(explorer.getByText(/baseDamage:damage.*trace:ratio.*retention:ratio/)).toBeVisible();
  const source = explorer.getByRole("link", { name: /Pinned F# source · CombatRules.damage/ });
  if (process.env.SIR_RULES_EXPLORER_MUTATE_SUBJECT === "source") {
    await source.evaluate((node) => node.setAttribute("href", "https://example.invalid/mutated-source"));
  }
  await expect(source).toHaveAttribute(
    "href",
    `https://github.com/EHotwagner/S.I.R./blob/${rulesImplementationSources.sourceCommit}/src/SIR.Simulation/CombatRules.fs`,
  );
  await expect(damageRule.getByText(/examples: tests\/SIR\.Conformance\.Shared\/RulesCorpusFixtures\.fs · properties:/)).toBeVisible();
  await expect(damageRule.getByRole("link", { name: "Coverage graph" })).toHaveAttribute("href", /rules-corpus\/v2\/coverage\.json/);

  const drill = explorer.getByRole("region", { name: "Physical combat drill", exact: true });
  await expect(drill.getByRole("button", { name: "Run four-profile combat scenario" })).toBeEnabled();
  const authorityResponse = page.waitForResponse((response) => response.url().includes("/api/combat/physical-drill") && response.status() === 200);
  await drill.getByRole("button", { name: "Run four-profile combat scenario" }).click();
  const response = await authorityResponse;
  const responseBody = await response.text();
  expect(physicalAuthorityRequests).toBe(1);
  await expect(drill.getByText("Cover integrity 50 → 0 · destroyed true", { exact: true })).toBeVisible();
  if (process.env.SIR_RULES_EXPLORER_MUTATE_SUBJECT === "replay") {
    await drill.getByText(/Replay v6 verified true/).evaluate((node) => { node.textContent = node.textContent.replace("Replay v6", "Replay v5"); });
  }
  await expect(drill.getByText(/Replay v6 verified true from 4 seek points · final tick 4 · state [0-9a-f]{64}/)).toBeVisible();

  const expectedProfiles = [
    ["Rifle", "50 → 38 · destroyed false"],
    ["SupportWeapon", "38 → 38 · destroyed false"],
    ["AntiArmor", "38 → 13 · destroyed false"],
    ["LobbedArea", "13 → 0 · destroyed true"],
  ];
  for (const [profile, coverIntegrity] of expectedProfiles) {
    const outcome = drill.getByRole("article", { name: `${profile} authoritative outcome`, exact: true });
    await expect(outcome).toBeVisible();
    await expect(outcome.getByRole("heading", { name: profile, exact: true })).toBeVisible();
    await expect(outcome.getByLabel(`${profile} visible attack trace`, { exact: true })).toBeVisible();
    await expect(outcome.getByText(coverIntegrity, { exact: true })).toBeVisible();
    await expect(outcome.getByRole("list")).toContainText("HP");
    await expect(outcome.getByRole("list")).toContainText("Suppression");
  }
  const antiArmor = drill.getByRole("article", { name: "AntiArmor authoritative outcome", exact: true });
  await expect(antiArmor.getByText(/roadblock-2 · retained 50%/)).toBeVisible();
  await expect(antiArmor.getByText(/Front rating 50 vs penetration 70 · retained 100%/)).toBeVisible();
  await expect(antiArmor.getByText("67 / Serious", { exact: true })).toBeVisible();
  const antiArmorExplanation = antiArmor.getByRole("list");
  await expect(antiArmorExplanation).toContainText("Physical trace");
  await expect(antiArmorExplanation).toContainText("Cover");
  await expect(antiArmorExplanation).toContainText("Armor");
  await expect(antiArmorExplanation).toContainText("Wound");
  console.log(JSON.stringify({ schema: "sir-physical-combat-route-v1", authorityRequests: physicalAuthorityRequests, responseBytes: Buffer.byteLength(responseBody, "utf8") }));
});

test("the production browser consumes only the observer-local awareness and reaction projection", async ({ page }) => {
  let authorityRequests = 0;
  page.on("request", (request) => {
    if (request.url().includes("/api/awareness/local-projection")) authorityRequests += 1;
  });
  await page.goto("/");
  await page.getByRole("button", { name: "View", exact: true }).click();
  await page.getByRole("menuitem", { name: /Rules data/ }).click();
  const projection = page.getByRole("region", { name: "Local awareness and reaction projection", exact: true });
  const act = async (name) => {
    const responsePromise = page.waitForResponse((response) => response.url().includes("/api/awareness/local-projection") && response.status() === 200);
    await projection.getByRole("button", { name }).click();
    return responsePromise;
  };
  await act("Reset awareness drill");
  await act("Rotate attention east");
  await act("Prepare covered sector");
  await act("Complete preparation");
  const response = await act("Move opposing unit through coverage");
  let body = await response.text();
  if (process.env.SIR_AWARENESS_BROWSER_MUTATE_SUBJECT === "projection") {
    const mutated = JSON.parse(body);
    mutated.Contacts = [];
    body = JSON.stringify(mutated);
  }
  const responseSubject = JSON.parse(body);
  expect(authorityRequests).toBe(5);
  expect(body).not.toContain("Units");
  expect(body).not.toContain("Board");
  expect(body).not.toContain("SpatialEvidence");
  expect(responseSubject.Contacts).toHaveLength(1);
  expect(responseSubject.Stimuli).toHaveLength(1);
  await expect(projection.getByText(/Observer 10 · tick 5 · contacts 1 · candidate pairs 2 · LOS 2/)).toBeVisible();
  await expect(projection.getByRole("heading", { name: "Contact 20 · Acquired" })).toBeVisible();
  await expect(projection.getByText(/Engagement player-area-east · area:2,0 · attention East · posture Prepared · Resolved · ResolvedByPhysicalAuthority/)).toBeVisible();
  await expect(projection.getByText("Authoritative order committed:10:20:player-area-east → physical:10 → resolved:10:20:player-area-east", { exact: true })).toBeVisible();
  await act("Scrub awareness timeline to start");
  await expect(projection.getByText(/Observer 10 · tick 1/)).toBeVisible();
  await act("Scrub awareness timeline to reaction");
  await expect(projection.getByText(/Observer 10 · tick 5/)).toBeVisible();
  expect(authorityRequests).toBe(7);
  console.log(JSON.stringify({ schema: "sir-local-awareness-browser-v1", authorityRequests, responseBytes: Buffer.byteLength(body, "utf8") }));
});

test("the player-visible spatial diagnostics route shows authoritative selected-unit evidence", async ({ page }) => {
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  await battlefield.locator("#persistent-layer-units [data-unit-id]").first().click();
  await page.getByRole("button", { name: "View", exact: true }).click();
  await page.getByRole("menuitem", { name: /Spatial diagnostics/ }).click();
  const diagnostics = page.getByRole("region", { name: "Selected unit spatial diagnostics", exact: true });
  await expect(diagnostics).toBeVisible();
  await expect(diagnostics.getByText(/ExactLineOfSight · Found/)).toBeVisible();
  await expect(diagnostics.getByText(/BoundedPath · Found/)).toBeVisible();
  await expect(diagnostics.getByText(/Cover · Found/)).toBeVisible();
  await expect(diagnostics.getByText("Normalized inputs", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Footprint samples", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Authoritative path", { exact: true }).first()).toBeVisible();
  const boundedPath = diagnostics.locator("details").filter({ hasText: "BoundedPath · Found" });
  const renderedPath = boundedPath.getByText("Authoritative path", { exact: true }).locator("+ dd");
  await expect(renderedPath).not.toHaveText("none");
  await expect(renderedPath).toHaveText(/^\(\d+,\d+\)(?:, \(\d+,\d+\))+$/);
  await expect(diagnostics.getByText("Crossed cells", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Crossed edges", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Cover contributors", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Decisions", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Expansion / truncation", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText(/player-disclosed/).first()).toBeVisible();
  await expect(diagnostics.getByText(/FS\.GG\.Game\.Core@0\.13\.0.*fs-gg-game-core-fable-lockstep-v1/).first()).toBeVisible();
  await expect(diagnostics.getByText("SIR.Simulation.SpatialQuery.evaluate", { exact: true }).first()).toBeVisible();
});

test("the maintained simulation transport is available without a manual handoff in every modality", async ({ page }) => {
  await loadMaintainedSimulation(page);
  for (const mode of ["Editor", "Plan", "Simulate", "Review"]) {
    await switchWorkspace(page, mode);
    await page.getByRole("button", { name: "Simulation", exact: true }).click();
    await expect(page.getByRole("menu", { name: "Simulation commands" }).getByRole("menuitem", { name: /^Play or pause/ })).toBeEnabled();
    await page.keyboard.press("Escape");
  }
  await expect(page.getByText(/simulator handoff/i)).toHaveCount(0);
});

test("maintained runtime state is truthful at the cursor in every modality", async ({ page }) => {
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  const unit = battlefield.locator("#persistent-layer-units [data-unit-id]").first();
  await unit.click();
  await page.locator("#unit-controller").selectOption({ label: "Scripted AI" });
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  const runtimeUnits = await observableUnitState(battlefield);
  expect(runtimeUnits[0].status).toContain("scripted");
  for (const mode of ["Simulate", "Editor", "Plan", "Review"]) {
    await switchWorkspace(page, mode);
    const expectedOwner = mode === "Simulate" ? "SimulatorScene" : mode === "Plan" ? "PlanningScene" : "EditorScene";
    await expect(battlefield).toHaveAttribute("data-scene-owner", expectedOwner);
    await expect(battlefield).toHaveAttribute("data-scene-tick", "1");
    await expect(page.getByLabel("Unified tactical timeline")).toHaveAttribute("data-time-cursor", "1");
    expect(await observableUnitState(battlefield)).toEqual(runtimeUnits);
  }
});

test("advance pause place seek activation and resume preserve continuous state", async ({ page }) => {
  await loadMaintainedSimulation(page);
  await page.getByRole("button", { name: "View", exact: true }).click();
  await page.getByRole("menu", { name: "View commands" }).getByRole("menuitemcheckbox", { name: "Timeline", exact: true }).click();
  const battlefield = page.locator("#persistent-tactical-svg");
  const play = page.getByRole("button", { name: "Play tactical timeline", exact: true });
  const pause = page.getByRole("button", { name: "Pause tactical timeline", exact: true });
  await play.click();
  await expect(pause).toBeVisible();
  await expect.poll(async () => Number(await battlefield.getAttribute("data-scene-tick"))).toBeGreaterThan(0);
  await pause.click();
  await expect(play).toBeVisible();
  const activationTick = Number(await battlefield.getAttribute("data-scene-tick"));
  await page.waitForTimeout(250);
  await expect(battlefield).toHaveAttribute("data-scene-tick", String(activationTick));
  const originalUnitCount = await battlefield.locator("#persistent-layer-units [data-unit-id]").count();
  const existingBefore = await observableUnitState(battlefield);
  const existingIds = existingBefore.map((unit) => unit.id);

  await switchWorkspace(page, "Editor");
  const tools = await expandPanel(page, "tools");
  await tools.getByRole("button", { name: "Units", exact: true }).click();
  await tools.locator(".unit-preset-group button").first().click();
  await battlefield.locator('[aria-label="Activate cell 12,4"]').click();
  await switchWorkspace(page, "Simulate");
  await expect(page.getByText(`Added 1 unit(s) at tick ${activationTick}.`, { exact: true })).toBeVisible();
  await expect(battlefield.locator("#persistent-layer-units [data-unit-id]")).toHaveCount(originalUnitCount + 1);
  expect(await observableUnitState(battlefield, existingIds)).toEqual(existingBefore);
  const liveActivationState = await battlefield.locator("#persistent-layer-units").innerHTML();

  await page.getByRole("button", { name: "Go to tactical timeline start", exact: true }).click();
  await expect(battlefield).toHaveAttribute("data-scene-tick", "0");
  await expect(battlefield.locator("#persistent-layer-units [data-unit-id]")).toHaveCount(originalUnitCount);
  const slider = page.getByRole("slider", { name: "Current tactical time", exact: true });
  if (activationTick > 1) {
    await slider.fill(String(activationTick - 1));
    await expect(battlefield).toHaveAttribute("data-scene-tick", String(activationTick - 1));
    await expect(battlefield.locator("#persistent-layer-units [data-unit-id]")).toHaveCount(originalUnitCount);
  }
  await page.getByRole("button", { name: "Step tactical timeline forward", exact: true }).click();
  await expect(battlefield).toHaveAttribute("data-scene-tick", String(activationTick));
  await expect(battlefield.locator("#persistent-layer-units")).toHaveJSProperty("innerHTML", liveActivationState);

  await play.click();
  await expect(pause).toBeVisible();
  await expect.poll(async () => Number(await battlefield.getAttribute("data-scene-tick"))).toBeGreaterThan(activationTick);
  await pause.click();
  await expect(play).toBeVisible();
  const finalPausedTick = await battlefield.getAttribute("data-scene-tick");
  await page.waitForTimeout(250);
  await expect(battlefield).toHaveAttribute("data-scene-tick", finalPausedTick);
});

test("terrain edits reset with a terrain-specific visible explanation", async ({ page }) => {
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await switchWorkspace(page, "Editor");
  const tools = await expandPanel(page, "tools");
  await tools.getByRole("button", { name: "Terrain", exact: true }).click();
  await tools.getByRole("button", { name: "Pencil", exact: true }).click();
  await tools.getByRole("button", { name: /^rough terrain,/i }).click();
  await battlefield.focus();
  await battlefield.press("Enter");
  await tools.getByRole("button", { name: /^blocked terrain,/i }).click();
  await battlefield.focus();
  await battlefield.press("Enter");
  await switchWorkspace(page, "Simulate");
  await expect(page.getByText("Simulation restarted at tick 0 because terrain changed.", { exact: true })).toBeVisible();
});

test("topology edits reset with a topology-specific visible explanation", async ({ page }) => {
  await loadMaintainedSimulation(page);
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await switchWorkspace(page, "Editor");
  const edgeTools = await expandPanel(page, "tools");
  await edgeTools.getByRole("button", { name: "Edges", exact: true }).click();
  await edgeTools.getByRole("button", { name: "Convert cursor edge to wall", exact: true }).click();
  await edgeTools.getByRole("button", { name: "Convert cursor edge to a window", exact: true }).click();
  await switchWorkspace(page, "Simulate");
  await expect(page.getByText("Simulation restarted at tick 0 because edge topology changed.", { exact: true })).toBeVisible();
});

test("the normal UI remains operable at 400 percent browser zoom", async ({ page }) => {
  await page.goto("/");
  // Browser-zoom environment model: quarter the CSS viewport and raise DPR to
  // four, which exercises the same responsive media queries as 400% zoom.
  const cdp = await page.context().newCDPSession(page);
  await cdp.send("Emulation.setDeviceMetricsOverride", {
    width: 320,
    height: 180,
    deviceScaleFactor: 4,
    mobile: false,
  });
  await expect.poll(() => page.evaluate(() => window.innerWidth)).toBeLessThanOrEqual(320);
  await expect.poll(() => page.evaluate(() => window.devicePixelRatio)).toBeGreaterThanOrEqual(4);
  await expect(page.getByRole("main", { name: "S.I.R. simulator and editor" })).toBeVisible();
  await switchWorkspace(page, "Simulate");
  await openSamples(page);
  const samplesOwner = page.getByLabel("Curated samples feature", { exact: true });
  await expect(samplesOwner).toBeVisible();
  await expect(samplesOwner.getByRole("region", { name: "Curated maps simulations and replays", exact: true })).toBeVisible();
});

test("a valid map selected through the visible import control reports success", async ({ page }) => {
  await page.goto("/");
  await switchWorkspace(page, "Editor");
  await page.getByRole("button", { name: "Expand Document / revision panel", exact: true }).click();
  const picker = page.getByLabel("Import SIR map", { exact: true });
  await expect(picker).toBeVisible();
  await picker.setInputFiles({
    name: "invalid.sir-map",
    mimeType: "text/plain",
    buffer: Buffer.from("not a SIR map"),
  });
  await expect(page.getByRole("alert")).toContainText(/not a supported|Map line/i);
  await picker.setInputFiles({
    name: "visible-success.sir-map",
    mimeType: "text/plain",
    buffer: Buffer.from("SIR-MAP 2\nsize 4 4\n"),
  });
  await expect(page.getByRole("alert")).toContainText("Imported map visible-success.sir-map.");
});

test("the visible replay picker rejects corruption then loads the engine-bound retained package", async ({ page }) => {
  await page.goto("/");
  await switchWorkspace(page, "Review");
  const picker = page.getByLabel("Choose replay package", { exact: true });
  await expect(picker).toBeVisible();
  const corrupt = Buffer.from(retainedReplay);
  corrupt[corrupt.length - 1] ^= 0x01;
  await picker.setInputFiles({ name: "corrupt.sirr", mimeType: "application/octet-stream", buffer: corrupt });
  await expect(page.getByText(/corrupt\.sirr rejected:/)).toBeVisible();
  await picker.setInputFiles({ name: "retained.sirr", mimeType: "application/octet-stream", buffer: retainedReplay });
  await expect(page.getByText(/Loaded retained\.sirr/)).toBeVisible();
});

test("the visible background picker rejects an oversized file then reports attachment", async ({ page }) => {
  await page.goto("/");
  await switchWorkspace(page, "Editor");
  await page.getByRole("button", { name: "Expand Document / revision panel", exact: true }).click();
  const picker = page.getByLabel("Choose local raster map background", { exact: true });
  await expect(picker).toBeVisible();
  await picker.setInputFiles({ name: "too-large.png", mimeType: "image/png", buffer: Buffer.alloc(10_485_761) });
  await expect(page.getByRole("alert")).toContainText(/allowed maximum/i);
  await picker.setInputFiles({
    name: "attached.png",
    mimeType: "image/png",
    buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL9bQAAAABJRU5ErkJggg==", "base64"),
  });
  await expect(page.getByRole("alert")).toContainText("Attached background attached.png.");
});

test("a curated sample exposes maintained playback and can reset", async ({ page }) => {
  await loadMaintainedSimulation(page);

  const runtimeTick = page.getByText(/Authoritative runtime tick \d+/);
  await page.getByRole("button", { name: "Simulation", exact: true }).click();
  await page.getByRole("menu", { name: "Simulation commands" }).getByRole("menuitem", { name: /^Play or pause/ }).click();
  await expect(runtimeTick).not.toHaveText(/^Authoritative runtime tick 0\b/);
  await page.getByRole("button", { name: "Simulation", exact: true }).click();
  await page.getByRole("menu", { name: "Simulation commands" }).getByRole("menuitem", { name: /^Play or pause/ }).click();
  const beforeTick = Number((await runtimeTick.textContent()).match(/\d+/)[0]);
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await expect(runtimeTick).toHaveText(new RegExp(`^Authoritative runtime tick ${beforeTick + 1}\\b`));
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "Reset simulation to the current authored baseline", exact: true }).filter({ hasText: "Reset simulation" }).click();
  await expect(page.getByText(/Authoritative runtime tick 0/)).toBeVisible();
});

test("production simulator status exposes continuous runtime time without handoff chrome", async ({ page }) => {
  await loadMaintainedSimulation(page);
  await expect(page.getByText(/^Authoritative runtime tick 0/)).toBeVisible();
  await expect(page.getByText(/manual.*handoff/i)).toHaveCount(0);
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await expect(page.getByText(/^Authoritative runtime tick 1/)).toBeVisible();
});

test("live authority reconnect remains visible through the production command surface", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Simulation", exact: true }).click();
  await expect(page.getByRole("menu", { name: "Simulation commands" })).toBeVisible();
  const live = page.getByRole("region", { name: "Authoritative live session" });
  await expect(live).toContainText("live connected", { timeout: 90_000 });
  await page.getByRole("menuitem", { name: "Send the next player-visible live advance command" }).click();
  await expect(live).toContainText(/tick [1-9]/, { timeout: 30_000 });
  await page.getByRole("menuitem", { name: "Disconnect the player-visible live session" }).click();
  await expect(live).toContainText("live disconnected");
  await page.getByRole("menuitem", { name: "Reconnect and request the authoritative live snapshot" }).click();
  await expect(live).toContainText("live connected");
});
