import { allowExpectedDiagnostic, expect, test } from "./journey.js";
import { readFileSync } from "node:fs";

// Generated by the canonical SIR.Simulation.Replay encoder from the retained
// PerspectivePlayback package used by SIR.Client.Tests; the engine hash is
// intentionally embedded so a changed engine rejects this fixture.
const retainedReplay = Buffer.from(
  readFileSync(new URL("../fixtures/retained-perspective-replay.sirr.base64", import.meta.url), "utf8").trim(),
  "base64",
);

async function loadMaintainedSimulation(page) {
  await page.goto("/");
  await page.getByRole("button", { name: "Simulate", exact: true }).click();
  await page.getByRole("button", { name: "Show contextual actions", exact: true }).click();
  await page.getByRole("button", { name: "Open simulator samples", exact: true }).click();
  await page.getByRole("button", { name: /^Load simulation sample:/ }).first().click();
}

async function expandPanel(page, panelId) {
  const panel = page.locator(`[data-panel-id="${panelId}"]`);
  if (await panel.count() === 0) {
    await page.locator("details.tactical-panel-menu").click();
    await page.locator(`#layout-show-${panelId}`).click();
  }
  if (await panel.getAttribute("data-collapsed") === "true" || await panel.evaluate((node) => node.classList.contains("is-collapsed"))) {
    await panel.locator(`#layout-panel-${panelId}-collapse`).click();
  }
  await expect(panel).toBeVisible();
  return panel;
}

async function observableUnitState(battlefield, unitIds = null) {
  return battlefield.locator("#persistent-layer-units [data-unit-id]").evaluateAll((units, retainedIds) =>
    units
      .filter((unit) => retainedIds === null || retainedIds.includes(unit.getAttribute("data-unit-id")))
      .map((unit) => ({
        id: unit.getAttribute("data-unit-id"),
        classId: unit.getAttribute("data-unit-class"),
        footprint: unit.getAttribute("data-unit-footprint"),
        status: unit.getAttribute("data-unit-status"),
        stance: unit.getAttribute("data-unit-stance"),
        column: unit.getAttribute("data-presentation-column"),
        row: unit.getAttribute("data-presentation-row"),
        // Capture the complete rendered runtime payload: glyph, label, health,
        // status markers, and direction geometry.
        rendered: unit.innerHTML,
        headings: [...unit.querySelectorAll("[data-unit-heading]")].map((heading) => ({
          kind: heading.getAttribute("data-unit-heading"),
          x1: heading.getAttribute("x1"),
          y1: heading.getAttribute("y1"),
          x2: heading.getAttribute("x2"),
          y2: heading.getAttribute("y2"),
        })),
      }))
      .sort((left, right) => Number(left.id) - Number(right.id)),
    unitIds,
  );
}

// Diagnostics-gate self-tests deliberately issue a browser fetch; they are not product-journey evidence.
test("explicitly allowed rejection diagnostics do not hide unrelated browser failures", async ({ page }) => {
  await page.route("**/controlled-rejection", (route) => route.fulfill({ status: 418, body: "expected" }));
  allowExpectedDiagnostic(page, /controlled-rejection|I'm a teapot/);
  await page.goto("/");
  await page.evaluate(() => fetch("/controlled-rejection"));
});

test("unexpected rejection diagnostics fail the journey gate", async ({ page }) => {
  test.skip(process.env.SIR_DIAGNOSTIC_SELF_TEST !== "1", "diagnostic gate child-process self-test only");
  await page.route("**/unexpected-rejection", (route) => route.fulfill({ status: 418, body: "unexpected" }));
  // Isolate the network threshold: Chromium emits a generic 418 console message
  // for fetch, while this child specifically proves the unallowlisted response gate.
  allowExpectedDiagnostic(page, /I'm a teapot/);
  await page.goto("/");
  await page.evaluate(() => fetch("/unexpected-rejection"));
});

test("visible mode controls preserve a usable tactical workspace across authoring modes", async ({ page }) => {
  await page.goto("/");
  const workspace = page.getByRole("main", { name: "S.I.R. simulator and editor" });
  await expect(workspace).toBeVisible();

  for (const mode of ["Editor", "Plan", "Simulate", "Review"]) {
    const control = page.getByRole("button", { name: mode, exact: true });
    await control.click();
    await expect(control).toHaveAttribute("aria-pressed", "true");
    await expect(workspace.getByRole("application")).toBeVisible();
  }
});

test("the player-visible Rules explorer renders the executable combat corpus and pinned source", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "View", exact: true }).click();
  await page.getByRole("menuitem", { name: /Rules data/ }).click();
  const explorer = page.getByRole("region", { name: "Rules data tables", exact: true });
  await expect(explorer).toBeVisible();
  await expect(explorer.getByRole("heading", { name: /FS\.GG\.Game\.Core@0\.13\.0/ })).toBeVisible();
  await expect(explorer.getByRole("heading", { name: /AttackResolved event/ })).toHaveCount(0);
  await explorer.getByRole("button", { name: "Execute canonical player attack" }).click();
  await expect(explorer.getByRole("heading", { name: "AttackResolved event tick-1-attack-10-20" })).toBeVisible();
  await expect(explorer.getByText(/Damage 25 · remaining health 75/)).toBeVisible();
  await expect(explorer.getByText(/COMBAT-DAMAGE-001.*baseDamage=.*trace=.*retention=.*→.*damage/)).toBeVisible();
  await explorer.getByRole("link", { name: "Open governing rule COMBAT-ATTACK-RESOLUTION-001" }).click();
  await expect(page).toHaveURL(/#rule-COMBAT-ATTACK-RESOLUTION-001$/);
  await expect(explorer.getByText(/Transition · AttackPhase · events AttackResolved/)).toBeVisible();
  const damage = explorer.getByText(/^COMBAT-DAMAGE-001 · Expected damage$/);
  await damage.click();
  const damageRule = damage.locator("..");
  await expect(explorer.getByText(/baseDamage:damage.*trace:ratio.*retention:ratio/)).toBeVisible();
  const source = explorer.getByRole("link", { name: /Pinned F# source · CombatRules.damage/ });
  await expect(source).toHaveAttribute(
    "href",
    /github\.com\/EHotwagner\/S\.I\.R\.\/blob\/9e778c966f1d978c6ea80141d6d42c5cc6c44218\/src\/SIR\.Simulation\/CombatRules\.fs/,
  );
  await expect(damageRule.getByText(/examples: tests\/SIR\.Conformance\.Shared\/RulesCorpusFixtures\.fs · properties:/)).toBeVisible();
  await expect(damageRule.getByRole("link", { name: "Coverage graph" })).toHaveAttribute("href", /rules-corpus\/v2\/coverage\.json/);
});

test("the maintained simulation transport is available without a manual handoff in every modality", async ({ page }) => {
  await loadMaintainedSimulation(page);
  for (const mode of ["Editor", "Plan", "Simulate", "Review"]) {
    await page.getByRole("button", { name: mode, exact: true }).click();
    await expect(page.getByRole("button", { name: "Play tactical timeline", exact: true })).toBeEnabled();
  }
  await expect(page.getByText(/simulator handoff/i)).toHaveCount(0);
});

test("maintained runtime state is truthful at the cursor in every modality", async ({ page }) => {
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  const unit = battlefield.locator("#persistent-layer-units [data-unit-id]").first();
  await unit.click();
  await page.locator("#unit-controller").selectOption({ label: "Scripted AI" });
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  const runtimeUnits = await observableUnitState(battlefield);
  expect(runtimeUnits[0].status).toContain("scripted");
  for (const mode of ["Simulate", "Editor", "Plan", "Review"]) {
    await page.getByRole("button", { name: mode, exact: true }).click();
    const expectedOwner = mode === "Simulate" ? "SimulatorScene" : mode === "Plan" ? "PlanningScene" : "EditorScene";
    await expect(battlefield).toHaveAttribute("data-scene-owner", expectedOwner);
    await expect(battlefield).toHaveAttribute("data-scene-tick", "1");
    await expect(page.getByLabel("Unified tactical timeline")).toHaveAttribute("data-time-cursor", "1");
    expect(await observableUnitState(battlefield)).toEqual(runtimeUnits);
  }
});

test("advance pause place seek activation and resume preserve continuous state", async ({ page }) => {
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  const play = page.getByRole("button", { name: "Play tactical timeline", exact: true });
  const pause = page.getByRole("button", { name: "Pause tactical timeline", exact: true });
  await play.click();
  await expect(pause).toBeVisible();
  await expect.poll(async () => Number(await battlefield.getAttribute("data-scene-tick"))).toBeGreaterThan(0);
  await pause.click();
  await expect(play).toBeVisible();
  const activationTick = Number(await battlefield.getAttribute("data-scene-tick"));
  await page.waitForTimeout(250);
  await expect(battlefield).toHaveAttribute("data-scene-tick", String(activationTick));
  const originalUnitCount = await battlefield.locator("#persistent-layer-units [data-unit-id]").count();
  const existingBefore = await observableUnitState(battlefield);
  const existingIds = existingBefore.map((unit) => unit.id);

  await page.getByRole("button", { name: "Editor", exact: true }).click();
  const tools = await expandPanel(page, "tools");
  await tools.getByRole("button", { name: "Units", exact: true }).click();
  await tools.locator(".unit-preset-group button").first().click();
  await battlefield.locator('[aria-label="Activate cell 12,4"]').click();
  await page.getByRole("button", { name: "Simulate", exact: true }).click();
  await expect(page.getByText(`Added 1 unit(s) at tick ${activationTick}.`, { exact: true })).toBeVisible();
  await expect(battlefield.locator("#persistent-layer-units [data-unit-id]")).toHaveCount(originalUnitCount + 1);
  expect(await observableUnitState(battlefield, existingIds)).toEqual(existingBefore);
  const liveActivationState = await battlefield.locator("#persistent-layer-units").innerHTML();

  await page.getByRole("button", { name: "Go to tactical timeline start", exact: true }).click();
  await expect(battlefield).toHaveAttribute("data-scene-tick", "0");
  await expect(battlefield.locator("#persistent-layer-units [data-unit-id]")).toHaveCount(originalUnitCount);
  const slider = page.getByRole("slider", { name: "Current tactical time", exact: true });
  if (activationTick > 1) {
    await slider.fill(String(activationTick - 1));
    await expect(battlefield).toHaveAttribute("data-scene-tick", String(activationTick - 1));
    await expect(battlefield.locator("#persistent-layer-units [data-unit-id]")).toHaveCount(originalUnitCount);
  }
  await page.getByRole("button", { name: "Step tactical timeline forward", exact: true }).click();
  await expect(battlefield).toHaveAttribute("data-scene-tick", String(activationTick));
  await expect(battlefield.locator("#persistent-layer-units")).toHaveJSProperty("innerHTML", liveActivationState);

  await play.click();
  await expect(pause).toBeVisible();
  await expect.poll(async () => Number(await battlefield.getAttribute("data-scene-tick"))).toBeGreaterThan(activationTick);
  await pause.click();
  await expect(play).toBeVisible();
  const finalPausedTick = await battlefield.getAttribute("data-scene-tick");
  await page.waitForTimeout(250);
  await expect(battlefield).toHaveAttribute("data-scene-tick", finalPausedTick);
});

test("terrain edits reset with a terrain-specific visible explanation", async ({ page }) => {
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await page.getByRole("button", { name: "Editor", exact: true }).click();
  const tools = await expandPanel(page, "tools");
  await tools.getByRole("button", { name: "Terrain", exact: true }).click();
  await tools.getByRole("button", { name: "Pencil", exact: true }).click();
  await tools.getByRole("button", { name: /^rough terrain,/i }).click();
  await battlefield.focus();
  await battlefield.press("Enter");
  await tools.getByRole("button", { name: /^blocked terrain,/i }).click();
  await battlefield.focus();
  await battlefield.press("Enter");
  await page.getByRole("button", { name: "Simulate", exact: true }).click();
  await expect(page.getByText("Simulation restarted at tick 0 because terrain changed.", { exact: true })).toBeVisible();
});

test("topology edits reset with a topology-specific visible explanation", async ({ page }) => {
  await loadMaintainedSimulation(page);
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await page.getByRole("button", { name: "Editor", exact: true }).click();
  const edgeTools = await expandPanel(page, "tools");
  await edgeTools.getByRole("button", { name: "Edges", exact: true }).click();
  await edgeTools.getByRole("button", { name: "Convert cursor edge to wall", exact: true }).click();
  await edgeTools.getByRole("button", { name: "Convert cursor edge to a window", exact: true }).click();
  await page.getByRole("button", { name: "Simulate", exact: true }).click();
  await expect(page.getByText("Simulation restarted at tick 0 because edge topology changed.", { exact: true })).toBeVisible();
});

test("the normal UI remains operable at 400 percent browser zoom", async ({ page }) => {
  await page.goto("/");
  // Browser-zoom environment model: quarter the CSS viewport and raise DPR to
  // four, which exercises the same responsive media queries as 400% zoom.
  const cdp = await page.context().newCDPSession(page);
  await cdp.send("Emulation.setDeviceMetricsOverride", {
    width: 320,
    height: 180,
    deviceScaleFactor: 4,
    mobile: false,
  });
  await expect.poll(() => page.evaluate(() => window.innerWidth)).toBeLessThanOrEqual(320);
  await expect.poll(() => page.evaluate(() => window.devicePixelRatio)).toBeGreaterThanOrEqual(4);
  await expect(page.getByRole("main", { name: "S.I.R. simulator and editor" })).toBeVisible();
  await page.getByRole("button", { name: "Simulate", exact: true }).click();
  await page.getByRole("button", { name: "Show contextual actions", exact: true }).click();
  await page.getByRole("button", { name: "Open simulator samples", exact: true }).click();
  await expect(page.getByLabel("Simulator samples", { exact: true })).toBeVisible();
});

test("a valid map selected through the visible import control reports success", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Editor", exact: true }).click();
  await page.getByRole("button", { name: "Expand Document / revision panel", exact: true }).click();
  const picker = page.getByLabel("Import SIR map", { exact: true });
  await expect(picker).toBeVisible();
  await picker.setInputFiles({
    name: "invalid.sir-map",
    mimeType: "text/plain",
    buffer: Buffer.from("not a SIR map"),
  });
  await expect(page.getByRole("alert")).toContainText(/not a supported|Map line/i);
  await picker.setInputFiles({
    name: "visible-success.sir-map",
    mimeType: "text/plain",
    buffer: Buffer.from("SIR-MAP 2\nsize 4 4\n"),
  });
  await expect(page.getByRole("alert")).toContainText("Imported map visible-success.sir-map.");
});

test("the visible replay picker rejects corruption then loads the engine-bound retained package", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Review", exact: true }).click();
  const picker = page.getByLabel("Choose replay package", { exact: true });
  await expect(picker).toBeVisible();
  const corrupt = Buffer.from(retainedReplay);
  corrupt[corrupt.length - 1] ^= 0x01;
  await picker.setInputFiles({ name: "corrupt.sirr", mimeType: "application/octet-stream", buffer: corrupt });
  await expect(page.getByText(/corrupt\.sirr rejected:/)).toBeVisible();
  await picker.setInputFiles({ name: "retained.sirr", mimeType: "application/octet-stream", buffer: retainedReplay });
  await expect(page.getByText(/Loaded retained\.sirr/)).toBeVisible();
});

test("the visible background picker rejects an oversized file then reports attachment", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Editor", exact: true }).click();
  await page.getByRole("button", { name: "Expand Document / revision panel", exact: true }).click();
  const picker = page.getByLabel("Choose local raster map background", { exact: true });
  await expect(picker).toBeVisible();
  await picker.setInputFiles({ name: "too-large.png", mimeType: "image/png", buffer: Buffer.alloc(10_485_761) });
  await expect(page.getByRole("alert")).toContainText(/allowed maximum/i);
  await picker.setInputFiles({
    name: "attached.png",
    mimeType: "image/png",
    buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL9bQAAAABJRU5ErkJggg==", "base64"),
  });
  await expect(page.getByRole("alert")).toContainText("Attached background attached.png.");
});

test("a curated sample exposes maintained playback and can reset", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Simulate", exact: true }).click();
  await page.getByRole("button", { name: "Show contextual actions", exact: true }).click();
  await page.getByRole("button", { name: "Open simulator samples", exact: true }).click();
  await page.getByRole("button", { name: /^Load simulation sample:/ }).first().click();

  const play = page.getByRole("button", { name: "Play tactical timeline", exact: true });
  await expect(play).toBeEnabled();
  await play.click();
  const pause = page.getByRole("button", { name: "Pause tactical timeline", exact: true });
  await expect(pause).toBeVisible();
  await pause.click();
  const runtimeTick = page.getByText(/Authoritative runtime tick \d+/);
  const beforeTick = Number((await runtimeTick.textContent()).match(/\d+/)[0]);
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await expect(runtimeTick).toHaveText(new RegExp(`^Authoritative runtime tick ${beforeTick + 1}\\b`));
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "Reset simulation to the current authored baseline", exact: true }).filter({ hasText: "Reset simulation" }).click();
  await expect(page.getByText(/Authoritative runtime tick 0/)).toBeVisible();
});

test("production simulator status exposes continuous runtime time without handoff chrome", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Simulate", exact: true }).click();
  await page.getByRole("button", { name: "Show contextual actions", exact: true }).click();
  await page.getByRole("button", { name: "Open simulator samples", exact: true }).click();
  await page.getByRole("button", { name: /^Load simulation sample:/ }).first().click();
  await expect(page.getByText(/^Authoritative runtime tick 0/)).toBeVisible();
  await expect(page.getByText(/manual.*handoff/i)).toHaveCount(0);
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await expect(page.getByText(/^Authoritative runtime tick 1/)).toBeVisible();
});

test("live authority reconnect remains visible through the production command surface", async ({ page }) => {
  await page.goto("/");
  const live = page.getByRole("region", { name: "Authoritative live session" });
  await expect(live).toContainText("live connected", { timeout: 90_000 });
  await page.getByRole("button", { name: "Send the next player-visible live advance command" }).click();
  await expect(live).toContainText(/tick [1-9]/, { timeout: 30_000 });
  await page.getByRole("button", { name: "Disconnect the player-visible live session" }).click();
  await expect(live).toContainText("live disconnected");
  await page.getByRole("button", { name: "Reconnect and request the authoritative live snapshot" }).click();
  await expect(live).toContainText("live connected");
});
