import { allowExpectedDiagnostic, expect, openSamples, switchWorkspace, test } from "./journey.js";
import { readFileSync } from "node:fs";

// Generated by the canonical SIR.Simulation.Replay encoder from the retained
// PerspectivePlayback package used by SIR.Client.Tests; the engine hash is
// intentionally embedded so a changed engine rejects this fixture.
const retainedReplay = Buffer.from(
  readFileSync(new URL("../fixtures/retained-perspective-replay.sirr.base64", import.meta.url), "utf8").trim(),
  "base64",
);
const rulesImplementationSources = JSON.parse(
  readFileSync(new URL("../fixtures/rules-corpus/v2/implementation-sources.json", import.meta.url), "utf8"),
);

async function loadMaintainedSimulation(page) {
  await page.goto("/");
  await switchWorkspace(page, "Simulate");
  await openSamples(page);
  const samplesOwner = page.getByLabel("Curated samples feature", { exact: true });
  await expect(samplesOwner).toBeVisible();
  await expect(samplesOwner.getByRole("region", { name: "Curated maps simulations and replays", exact: true })).toBeVisible();
  await samplesOwner.getByText("Troll assault", { exact: true }).click();
  await samplesOwner.getByRole("button", { name: "Run Troll assault in Simulator", exact: true }).click();
}

async function expandPanel(page, panelId) {
  const panel = page.locator(`[data-panel-id="${panelId}"]`);
  if (await panel.count() === 0) {
    await page.locator("details.tactical-panel-menu").click();
    await page.locator(`#layout-show-${panelId}`).click();
  }
  if (await panel.getAttribute("data-collapsed") === "true" || await panel.evaluate((node) => node.classList.contains("is-collapsed"))) {
    await panel.locator(`#layout-panel-${panelId}-collapse`).click();
  }
  await expect(panel).toBeVisible();
  return panel;
}

async function observableUnitState(battlefield, unitIds = null) {
  return battlefield.locator("#persistent-layer-units [data-unit-id]").evaluateAll((units, retainedIds) =>
    units
      .filter((unit) => retainedIds === null || retainedIds.includes(unit.getAttribute("data-unit-id")))
      .map((unit) => ({
        id: unit.getAttribute("data-unit-id"),
        classId: unit.getAttribute("data-unit-class"),
        footprint: unit.getAttribute("data-unit-footprint"),
        status: unit.getAttribute("data-unit-status"),
        stance: unit.getAttribute("data-unit-stance"),
        column: unit.getAttribute("data-presentation-column"),
        row: unit.getAttribute("data-presentation-row"),
        // Capture the complete rendered runtime payload: glyph, label, health,
        // status markers, and direction geometry.
        rendered: unit.innerHTML,
        headings: [...unit.querySelectorAll("[data-unit-heading]")].map((heading) => ({
          kind: heading.getAttribute("data-unit-heading"),
          x1: heading.getAttribute("x1"),
          y1: heading.getAttribute("y1"),
          x2: heading.getAttribute("x2"),
          y2: heading.getAttribute("y2"),
        })),
      }))
      .sort((left, right) => Number(left.id) - Number(right.id)),
    unitIds,
  );
}

// Diagnostics-gate self-tests deliberately issue a browser fetch; they are not product-journey evidence.
test("explicitly allowed rejection diagnostics do not hide unrelated browser failures", async ({ page }) => {
  await page.route("**/controlled-rejection", (route) => route.fulfill({ status: 418, body: "expected" }));
  allowExpectedDiagnostic(page, /controlled-rejection|I'm a teapot/);
  await page.goto("/");
  await page.evaluate(() => fetch("/controlled-rejection"));
});

test("unexpected rejection diagnostics fail the journey gate", async ({ page }) => {
  test.skip(process.env.SIR_DIAGNOSTIC_SELF_TEST !== "1", "diagnostic gate child-process self-test only");
  await page.route("**/unexpected-rejection", (route) => route.fulfill({ status: 418, body: "unexpected" }));
  // Isolate the network threshold: Chromium emits a generic 418 console message
  // for fetch, while this child specifically proves the unallowlisted response gate.
  allowExpectedDiagnostic(page, /I'm a teapot/);
  await page.goto("/");
  await page.evaluate(() => fetch("/unexpected-rejection"));
});

test("visible View commands preserve a usable tactical workspace across authoring modes", async ({ page }) => {
  await page.goto("/");
  const workspace = page.getByRole("main", { name: "S.I.R. simulator and editor" });
  await expect(workspace).toBeVisible();
  const battlefield = page.locator("#persistent-tactical-svg");
  const terrainGeometryBeforeModes = await battlefield.locator("#persistent-layer-terrain-geometry").getAttribute("data-geometry-constructions");
  const edgesGeometryBeforeModes = await battlefield.locator("#persistent-layer-edges-geometry").getAttribute("data-geometry-constructions");
  const unitGeometryBeforeModes = await battlefield.locator("#persistent-layer-units").getAttribute("data-geometry-constructions");
  const editorLayers = battlefield.locator("#persistent-editor-migrated-layers");
  const editorLayersConstructionsBeforeModes = await editorLayers.getAttribute("data-editor-layer-constructions");
  const viewMenu = page.getByRole("menu", { name: "View commands", includeHidden: true });
  const helpMenu = page.getByRole("menu", { name: "Help commands", includeHidden: true });
  const sharedSwitchEditorCommand = viewMenu.getByRole("menuitem", { name: /^Switch to Editor\b/, includeHidden: true });
  const selectedUnitDocumentation = helpMenu.getByRole("menuitem", { name: "Selected unit documentation", exact: true, includeHidden: true });
  const tacticalOverlayDocumentation = helpMenu.getByRole("menuitem", { name: "Tactical overlay documentation", exact: true, includeHidden: true });
  await expect(sharedSwitchEditorCommand).toHaveCount(1);
  await expect(selectedUnitDocumentation).toHaveCount(1);
  await expect(tacticalOverlayDocumentation).toHaveCount(1);
  await sharedSwitchEditorCommand.evaluate((shared, documentation) => {
    window.__sirSharedMenuCommand = shared;
    window.__sirSelectedDocumentationCommand = documentation[0];
    window.__sirOverlayDocumentationCommand = documentation[1];
  }, [await selectedUnitDocumentation.elementHandle(), await tacticalOverlayDocumentation.elementHandle()]);
  await editorLayers.evaluate((node) => {
    window.__sirEditorLayersNode = node;
    window.__sirEditorLayersChildMutations = [];
    window.__sirEditorLayersObserver = new MutationObserver((records) => {
      for (const record of records) {
        for (const changed of [...record.addedNodes, ...record.removedNodes]) {
          if (changed === window.__sirEditorLayersNode) window.__sirEditorLayersChildMutations.push(record.type);
        }
      }
    });
    window.__sirEditorLayersObserver.observe(node.parentElement, { childList: true });
  });
  const rosterHost = page.locator('[data-persistent-roster-host="true"]');
  const selectionHost = page.locator('[data-persistent-selection-host="true"]');
  const toolsHost = page.locator('[data-persistent-tools-host="true"]');
  await expect(rosterHost.locator("[data-roster-mode]")).toHaveCount(4);
  await expect(selectionHost.locator("[data-selection-mode]")).toHaveCount(4);
  await expect(toolsHost.locator("[data-tools-mode]")).toHaveCount(4);
  expect(await rosterHost.locator('[data-roster-mode][hidden] [id]').count()).toBe(0);
  await expect(page.locator("#persistent-tactical-svg")).toHaveCount(1);
  await expect(page.getByLabel("Unified tactical timeline")).toHaveCount(1);
  const editorRosterConstructions = await rosterHost.locator('[data-roster-mode="EditorWorkspace"] .persistent-roster-owner').getAttribute("data-roster-constructions");
  const editorSelectionConstructions = await selectionHost.locator('[data-selection-mode="EditorWorkspace"] .persistent-selection-owner').getAttribute("data-selection-constructions");
  const editorToolsConstructions = await toolsHost.locator('[data-tools-mode="EditorWorkspace"] .persistent-tools-owner').getAttribute("data-tools-constructions");

  for (const mode of ["Editor", "Plan", "Simulate", "Review"]) {
    await switchWorkspace(page, mode);
    await expect(workspace.getByRole("application")).toBeVisible();
    const workspaceMode = mode === "Editor" ? "EditorWorkspace" : mode === "Plan" ? "PlanningWorkspace" : mode === "Simulate" ? "SimulatorWorkspace" : "ReplayWorkspace";
    await expect(rosterHost.locator(`[data-roster-mode="${workspaceMode}"]`)).toBeVisible();
    await expect(rosterHost.locator(`[data-roster-mode="${workspaceMode}"]`)).not.toHaveAttribute("inert", "");
    await expect(rosterHost.locator("[data-roster-mode][hidden]")).toHaveCount(3);
    const inactiveAcceptedFocus = await rosterHost.locator("[data-roster-mode][hidden]").first().evaluate((owner) => {
      const candidate = owner.querySelector("button, input, select, [tabindex]");
      candidate?.focus();
      return candidate !== null && document.activeElement === candidate;
    });
    expect(inactiveAcceptedFocus).toBe(false);
    const activeSelection = selectionHost.locator(`[data-selection-mode="${workspaceMode}"]`);
    await expect(activeSelection).toBeVisible();
    await expect(activeSelection).not.toHaveAttribute("inert", "");
    await expect(selectionHost.locator("[data-selection-mode][hidden]")).toHaveCount(3);
    const inactiveSelectionAcceptedFocus = await selectionHost.locator("[data-selection-mode][hidden]").first().evaluate((owner) => {
      const candidate = owner.querySelector("button, input, select, textarea, [tabindex]");
      candidate?.focus();
      return candidate !== null && document.activeElement === candidate;
    });
    expect(inactiveSelectionAcceptedFocus).toBe(false);
    const inactiveSelectionIdsAreScoped = await selectionHost.locator("[data-selection-mode][hidden]").evaluateAll((owners) => owners.every((owner) => {
      const slug = owner.getAttribute("data-selection-mode") === "EditorWorkspace" ? "editor"
        : owner.getAttribute("data-selection-mode") === "PlanningWorkspace" ? "plan"
          : owner.getAttribute("data-selection-mode") === "SimulatorWorkspace" ? "simulate" : "review";
      const prefix = `inactive-${slug}-selection-`;
      return [...owner.querySelectorAll("[id]")].every((node) => node.id.startsWith(prefix))
        && [...owner.querySelectorAll("label[for]")].every((label) => {
          const target = label.getAttribute("for");
          return target.startsWith(prefix) && owner.querySelector(`#${CSS.escape(target)}`) !== null;
        });
    }));
    expect(inactiveSelectionIdsAreScoped).toBe(true);
    const duplicateIds = await page.locator("[id]").evaluateAll((nodes) => {
      const ids = nodes.map((node) => node.id);
      return ids.filter((id, index) => ids.indexOf(id) !== index);
    });
    expect(duplicateIds).toEqual([]);
    expect(await sharedSwitchEditorCommand.evaluate((node) => node === window.__sirSharedMenuCommand)).toBe(true);
    expect(await selectedUnitDocumentation.evaluate((node) => node === window.__sirSelectedDocumentationCommand)).toBe(true);
    expect(await tacticalOverlayDocumentation.evaluate((node) => node === window.__sirOverlayDocumentationCommand)).toBe(true);
    const simulatorControllerCommand = page.getByRole("menu", { name: "Simulation commands", includeHidden: true }).getByRole("menuitem", { name: /^Set controller Manual\b/, includeHidden: true });
    await expect(simulatorControllerCommand).toHaveCount(mode === "Simulate" ? 1 : 0);
    const activeTools = toolsHost.locator(`[data-tools-mode="${workspaceMode}"]`);
    await expect(activeTools).toBeVisible();
    await expect(activeTools).not.toHaveAttribute("inert", "");
    await expect(toolsHost.locator("[data-tools-mode][hidden]")).toHaveCount(3);
    const inactiveToolsSafe = await toolsHost.locator("[data-tools-mode][hidden]").evaluateAll((owners) => owners.every((owner) => {
      const slug = owner.getAttribute("data-tools-mode") === "EditorWorkspace" ? "editor"
        : owner.getAttribute("data-tools-mode") === "PlanningWorkspace" ? "plan"
          : owner.getAttribute("data-tools-mode") === "SimulatorWorkspace" ? "simulate" : "review";
      const prefix = `inactive-${slug}-tools-`;
      const focusable = owner.querySelector("button, input, select, textarea, [tabindex]");
      focusable?.focus();
      return document.activeElement !== focusable
        && [...owner.querySelectorAll("[id]")].every((node) => node.id.startsWith(prefix))
        && [...owner.querySelectorAll("label[for]")].every((label) => {
          const target = label.getAttribute("for");
          return target.startsWith(prefix) && owner.querySelector(`#${CSS.escape(target)}`) !== null;
        })
        && [...owner.querySelectorAll('input[type="file"]')].every((input) => input.files.length === 0);
    }));
    expect(inactiveToolsSafe).toBe(true);
    await expect(editorLayers).toHaveCount(1);
    expect(await editorLayers.evaluate((node) => node === window.__sirEditorLayersNode)).toBe(true);
    await expect(editorLayers).toHaveAttribute("data-editor-layer-constructions", editorLayersConstructionsBeforeModes);
    if (mode === "Editor") {
      await expect(editorLayers).toHaveAttribute("data-editor-layers-active", "true");
      await expect(editorLayers).toHaveAttribute("aria-hidden", "false");
    } else {
      await expect(editorLayers).toHaveAttribute("data-editor-layers-active", "false");
      await expect(editorLayers).toHaveAttribute("aria-hidden", "true");
      await expect(editorLayers).toHaveCSS("display", "none");
      const inactiveEditorLayersExposed = await editorLayers.evaluate((owner) => {
        const candidate = owner.querySelector("[tabindex], button, input, select, textarea, a[href]");
        candidate?.focus();
        return candidate !== null && document.activeElement === candidate;
      });
      expect(inactiveEditorLayersExposed).toBe(false);
    }
  }
  expect(await editorLayers.evaluate(() => { window.__sirEditorLayersObserver.disconnect(); return window.__sirEditorLayersChildMutations; })).toEqual([]);
  await switchWorkspace(page, "Editor");
  const zoomBeforeMenuCommand = Number(await battlefield.getAttribute("data-camera-zoom"));
  const battlefieldBox = await battlefield.boundingBox();
  await page.mouse.move(battlefieldBox.x + battlefieldBox.width / 2, battlefieldBox.y + battlefieldBox.height / 2);
  await page.mouse.wheel(0, -240);
  await expect.poll(async () => Number(await battlefield.getAttribute("data-camera-zoom"))).not.toBe(zoomBeforeMenuCommand);
  const zoomAfterWheel = Number(await battlefield.getAttribute("data-camera-zoom"));
  await page.getByRole("button", { name: "View", exact: true }).click();
  await viewMenu.getByRole("menuitem", { name: /^Fit the complete map\b/ }).click();
  await expect(viewMenu).toBeHidden();
  await expect.poll(async () => Number(await battlefield.getAttribute("data-camera-zoom"))).not.toBe(zoomAfterWheel);
  await expect(rosterHost.locator('[data-roster-mode="EditorWorkspace"] .persistent-roster-owner')).toHaveAttribute("data-roster-constructions", editorRosterConstructions);
  await expect(toolsHost.locator('[data-tools-mode="EditorWorkspace"] .persistent-tools-owner')).toHaveAttribute("data-tools-constructions", editorToolsConstructions);
  await expect(page.locator("#terrain-brush-size")).toHaveCount(1);
  const editorToolsBeforeChange = Number(editorToolsConstructions);
  await page.locator("#terrain-brush-size").fill("2");
  await expect.poll(async () => Number(await toolsHost.locator('[data-tools-mode="EditorWorkspace"] .persistent-tools-owner').getAttribute("data-tools-constructions"))).toBeGreaterThan(editorToolsBeforeChange);
  const activeEditorRoster = rosterHost.locator('[data-roster-mode="EditorWorkspace"]');
  const editorRosterBeforeSelection = Number(await activeEditorRoster.locator(".persistent-roster-owner").getAttribute("data-roster-constructions"));
  const firstEditorRosterCommand = activeEditorRoster.locator('button[aria-pressed="false"]').first();
  const firstEditorRosterCommandName = await firstEditorRosterCommand.textContent();
  const editorLayersBeforeSelection = Number(await editorLayers.getAttribute("data-editor-layer-constructions"));
  await firstEditorRosterCommand.click();
  await expect(activeEditorRoster.getByRole("button", { name: firstEditorRosterCommandName, exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect.poll(async () => Number(await activeEditorRoster.locator(".persistent-roster-owner").getAttribute("data-roster-constructions"))).toBeGreaterThan(editorRosterBeforeSelection);
  await expect.poll(async () => Number(await selectionHost.locator('[data-selection-mode="EditorWorkspace"] .persistent-selection-owner').getAttribute("data-selection-constructions"))).toBeGreaterThan(Number(editorSelectionConstructions));
  await expect.poll(async () => Number(await editorLayers.getAttribute("data-editor-layer-constructions"))).toBeGreaterThan(editorLayersBeforeSelection);
  await expect(page.locator("#editor-unit-controller")).toHaveCount(1);
  await switchWorkspace(page, "Simulate");
  const simulatorSelectionOwner = selectionHost.locator('[data-selection-mode="SimulatorWorkspace"] .persistent-selection-owner');
  const simulatorSelectionBefore = Number(await simulatorSelectionOwner.getAttribute("data-selection-constructions"));
  const simulatorRosterCommand = rosterHost.locator('[data-roster-mode="SimulatorWorkspace"] button[aria-pressed="false"]').first();
  const simulatorRosterCommandName = await simulatorRosterCommand.textContent();
  await simulatorRosterCommand.click();
  await expect(rosterHost.locator('[data-roster-mode="SimulatorWorkspace"]').getByRole("button", { name: simulatorRosterCommandName, exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect.poll(async () => Number(await simulatorSelectionOwner.getAttribute("data-selection-constructions"))).toBeGreaterThan(simulatorSelectionBefore);
  await expect(page.locator("#unit-controller")).toHaveCount(1);
  await expect(page.locator("#editor-unit-controller")).toHaveCount(1);
  await expect(page.locator("#persistent-tactical-svg")).toHaveCount(1);
  await expect(page.locator("#persistent-editor-migrated-layers")).toHaveCount(1);
  await expect(page.getByLabel("Unified tactical timeline")).toHaveCount(1);
  await switchWorkspace(page, "Review");
  await expect(page.locator("#replay-position")).toHaveCount(1);
  await expect(page.locator("#playback-speed")).toHaveCount(1);
  const activeReplayFile = toolsHost.locator('[data-tools-mode="ReplayWorkspace"] input[type="file"]');
  await expect(activeReplayFile).toHaveCount(1);
  await expect(activeReplayFile).toHaveAttribute("accept", ".sirr,application/octet-stream");
  await expect(activeReplayFile).toBeEnabled();
  await expect(battlefield.locator("#persistent-layer-terrain-geometry")).toHaveAttribute("data-geometry-constructions", terrainGeometryBeforeModes);
  await expect(battlefield.locator("#persistent-layer-edges-geometry")).toHaveAttribute("data-geometry-constructions", edgesGeometryBeforeModes);
  await expect(battlefield.locator("#persistent-layer-units")).toHaveAttribute("data-geometry-constructions", unitGeometryBeforeModes);
});

test("visible Plan worker status renders while background Plan completion stays isolated", async ({ page }) => {
  await page.addInitScript(() => {
    const nativePostMessage = Worker.prototype.postMessage;
    Worker.prototype.postMessage = function (...args) {
      setTimeout(() => nativePostMessage.apply(this, args), 100);
    };
  });
  await page.goto("/");
  const app = page.getByRole("main", { name: "S.I.R. simulator and editor" });
  const constructionsBeforePlan = Number(await app.getAttribute("data-app-view-constructions"));
  await switchWorkspace(page, "Plan");
  const documentPanel = await expandPanel(page, "document");
  const status = documentPanel.locator(".planning-worker-status");
  const planRoster = page.locator('[data-roster-mode="PlanningWorkspace"] .persistent-roster-owner');
  const planTools = page.locator('[data-tools-mode="PlanningWorkspace"] .persistent-tools-owner');
  const planSelection = page.locator('[data-selection-mode="PlanningWorkspace"] .persistent-selection-owner');
  const leftSidebar = page.locator("#tactical-sidebar-left");
  const rightSidebar = page.locator("#tactical-sidebar-right");
  const planRosterConstructionsBeforeReady = await planRoster.getAttribute("data-roster-constructions");
  const planToolsConstructionsBeforeReady = await planTools.getAttribute("data-tools-constructions");
  const planSelectionConstructionsBeforeReady = await planSelection.getAttribute("data-selection-constructions");
  const leftConstructionsBeforeReady = await leftSidebar.getAttribute("data-sidebar-constructions");
  const rightConstructionsBeforeReady = await rightSidebar.getAttribute("data-sidebar-constructions");
  const statusConstructionsBeforeReady = Number(await status.getAttribute("data-planning-worker-status-constructions"));
  await expect(status).toHaveText("Connecting to planning worker");
  await expect(status).toHaveText("Planning worker ready");
  await expect(planRoster).toHaveAttribute("data-roster-constructions", planRosterConstructionsBeforeReady);
  await expect(planTools).toHaveAttribute("data-tools-constructions", planToolsConstructionsBeforeReady);
  await expect(planSelection).toHaveAttribute("data-selection-constructions", planSelectionConstructionsBeforeReady);
  await expect(leftSidebar).toHaveAttribute("data-sidebar-constructions", leftConstructionsBeforeReady);
  await expect(rightSidebar).toHaveAttribute("data-sidebar-constructions", rightConstructionsBeforeReady);
  await expect(status).toHaveAttribute("data-planning-worker-status-constructions", String(statusConstructionsBeforeReady + 1));

  const planToolsBeforeToolChange = Number(await planTools.getAttribute("data-tools-constructions"));
  const planSelectionBeforeToolChange = Number(await planSelection.getAttribute("data-selection-constructions"));
  await planTools.getByRole("button", { name: /^Hold · H$/ }).click();
  await expect(planTools.getByRole("button", { name: /^Hold · H$/ })).toHaveAttribute("aria-pressed", "true");
  await expect.poll(async () => Number(await planTools.getAttribute("data-tools-constructions"))).toBeGreaterThan(planToolsBeforeToolChange);
  await expect.poll(async () => Number(await planSelection.getAttribute("data-selection-constructions"))).toBeGreaterThan(planSelectionBeforeToolChange);

  const planRosterBeforeSelection = Number(await planRoster.getAttribute("data-roster-constructions"));
  const planSelectionBeforeRosterSelection = Number(await planSelection.getAttribute("data-selection-constructions"));
  const alternateUnit = planRoster.locator('button[aria-pressed="false"]').first();
  const alternateUnitName = await alternateUnit.textContent();
  await alternateUnit.click();
  await expect(planRoster.getByRole("button", { name: alternateUnitName, exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect.poll(async () => Number(await planRoster.getAttribute("data-roster-constructions"))).toBeGreaterThan(planRosterBeforeSelection);
  await expect.poll(async () => Number(await planSelection.getAttribute("data-selection-constructions"))).toBeGreaterThan(planSelectionBeforeRosterSelection);
  expect(Number(await app.getAttribute("data-app-view-constructions"))).toBeGreaterThan(constructionsBeforePlan);
});

test("the production tactical visual system preserves causal feedback under reduced motion", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  await expect(battlefield).toHaveAttribute("data-visual-system", "tactical-visual-system-v1");
  await expect(battlefield).toHaveAttribute("data-motion", "reduced");
  await expect(battlefield).toHaveAttribute(
    "data-layer-order",
    "terrain>edges>routes>units>effects>selection>tactical-overlays>annotations",
  );
  const paintedOrder = await battlefield.locator("#persistent-scene-camera").evaluate((camera) =>
    [...camera.children].map((node) => node.getAttribute("data-scene-layer")).filter(Boolean).join(">"),
  );
  expect(paintedOrder).toBe(await battlefield.getAttribute("data-layer-order"));
  await expect(battlefield.locator("#persistent-layer-effects")).toHaveAttribute("data-effect-motion", "emphasis-120ms");

  const timeline = page.getByLabel("Unified tactical timeline");
  const timelineConstructionsBeforeAdvance = Number(await timeline.getAttribute("data-timeline-constructions"));
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await expect.poll(async () => Number(await timeline.getAttribute("data-timeline-constructions"))).toBeGreaterThan(timelineConstructionsBeforeAdvance);
  const effectCount = Number(await battlefield.getAttribute("data-effect-count"));
  const effectLimit = Number(await battlefield.getAttribute("data-effect-limit"));
  const unitCount = Number(await battlefield.getAttribute("data-visual-unit-count"));
  const nodeEstimate = Number(await battlefield.getAttribute("data-visual-node-estimate"));
  expect(effectCount).toBeGreaterThan(0);
  expect(effectCount).toBeLessThanOrEqual(effectLimit);
  expect(unitCount).toBeGreaterThan(0);
  expect(nodeEstimate).toBeLessThanOrEqual(unitCount <= 100 ? 5000 : 9000);
  const firstEffect = battlefield.locator("#persistent-layer-effects [data-effect-event]").first();
  await expect(firstEffect).toHaveAttribute("data-effect-kind", /movement|attack|impact|suppression|recovery|signal|objective|event/);
  await expect(firstEffect).toHaveAttribute("data-effect-lifecycle", /preview|predicted|accepted|committed|rejected|historical/);
  expect(await firstEffect.evaluate((node) => getComputedStyle(node).animationDuration)).toBe("0.12s");
  await expect(battlefield.locator("#persistent-layer-effects")).toHaveAttribute("pointer-events", "none");
  await expect(battlefield.locator("#persistent-layer-units [data-unit-id]").first()).toBeVisible();

  const samples = await battlefield.evaluate(async (root) => {
    const values = [];
    for (let index = 0; index < 24; index += 1) {
      await new Promise((resolve) => requestAnimationFrame(() => {
        const started = performance.now();
        root.querySelectorAll("[data-unit-id], [data-effect-event], [data-overlay-id]").length;
        values.push(performance.now() - started);
        resolve();
      }));
    }
    return values.sort((left, right) => left - right);
  });
  expect(samples[Math.floor(samples.length * 0.95)]).toBeLessThan(16.67);
});

test("large-project viewport chunking and semantic zoom bound the production SVG", async ({ page }) => {
  await page.setViewportSize({ width: 960, height: 640 });
  await page.goto("/");
  await switchWorkspace(page, "Editor");
  const documentPanel = await expandPanel(page, "document");
  const battlefield = page.locator("#persistent-tactical-svg");
  const terrainGeometryBeforeImport = Number(await battlefield.locator("#persistent-layer-terrain-geometry").getAttribute("data-geometry-constructions"));
  const edgesGeometryBeforeImport = Number(await battlefield.locator("#persistent-layer-edges-geometry").getAttribute("data-geometry-constructions"));
  const unitGeometryBeforeImport = Number(await battlefield.locator("#persistent-layer-units").getAttribute("data-geometry-constructions"));
  const lines = ["SIR-MAP 2", "size 40 40"];
  for (let index = 0; index < 200; index += 1) {
    const column = index % 40;
    // Keep the same 200-unit workload while distributing its five rows over
    // the complete map. A center-anchored semantic-zoom journey must retain
    // observable unit glyphs after viewport culling instead of accidentally
    // moving beyond a top-edge-only fixture.
    const row = Math.floor(index / 40) * 8;
    const script = Array(8).fill("E").join(",");
    lines.push(`unit ${index + 1} ${index % 2 ? "red" : "blue"} rifleman ${column} ${row} 1 12 12 scripted ${script}`);
  }
  await documentPanel.getByLabel("Import SIR map", { exact: true }).setInputFiles({
    name: "viewport-large-project.sir-map",
    mimeType: "text/plain",
    buffer: Buffer.from(`${lines.join("\n")}\n`),
  });
  await expect(page.getByRole("alert")).toContainText("Imported map viewport-large-project.sir-map.");
  await expect.poll(async () => Number(await battlefield.locator("#persistent-layer-terrain-geometry").getAttribute("data-geometry-constructions"))).toBeGreaterThan(terrainGeometryBeforeImport);
  await expect.poll(async () => Number(await battlefield.locator("#persistent-layer-edges-geometry").getAttribute("data-geometry-constructions"))).toBeGreaterThan(edgesGeometryBeforeImport);
  await expect.poll(async () => Number(await battlefield.locator("#persistent-layer-units").getAttribute("data-geometry-constructions"))).toBeGreaterThan(unitGeometryBeforeImport);
  await page.getByRole("button", { name: "Fit the complete map", exact: true }).click();

  const box = await battlefield.boundingBox();
  const viewBoxSize = await battlefield.evaluate((root) => [root.viewBox.baseVal.width, root.viewBox.baseVal.height]);
  expect(Math.abs(viewBoxSize[0] - box.width)).toBeLessThanOrEqual(1);
  expect(Math.abs(viewBoxSize[1] - box.height)).toBeLessThanOrEqual(1);
  for (let step = 0; step < 15; step += 1) {
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.wheel(0, -240);
  }
  await page.evaluate(() => new Promise((done) => requestAnimationFrame(() => requestAnimationFrame(done))));
  await expect.poll(async () => Number(await battlefield.getAttribute("data-viewport-queried-chunks"))).toBeLessThanOrEqual(24);
  const { emitted, candidates, global } = await battlefield.evaluate((root) => ({
    emitted: Number(root.dataset.viewportEmittedPrimitives),
    candidates: Number(root.dataset.viewportCandidatePrimitives),
    global: Number(root.dataset.viewportGlobalPrimitives),
  }));
  expect(emitted).toBeLessThanOrEqual(1600);
  expect(candidates).toBeGreaterThanOrEqual(emitted);
  expect(global).toBeGreaterThan(candidates);
  const primitiveIds = await battlefield.locator("[data-primitive-id]").evaluateAll((nodes) => nodes.map((node) => node.getAttribute("data-primitive-id")));
  expect(new Set(primitiveIds).size).toBe(primitiveIds.length);
  expect(await battlefield.locator('[data-unit-id][tabindex="0"]').count()).toBeLessThanOrEqual(1);

  const app = page.getByRole("main", { name: "S.I.R. simulator and editor" });
  const constructionsBeforePan = Number(await app.getAttribute("data-app-view-constructions"));
  const panBox = await battlefield.boundingBox();
  const cameraBeforePan = {
    panX: Number(await battlefield.getAttribute("data-camera-pan-x")),
    panY: Number(await battlefield.getAttribute("data-camera-pan-y")),
    zoom: Number(await battlefield.getAttribute("data-camera-zoom")),
  };
  expect(Math.abs(cameraBeforePan.panX) + Math.abs(cameraBeforePan.panY)).toBeGreaterThan(0);
  await page.mouse.move(panBox.x + panBox.width / 2, panBox.y + panBox.height / 2);
  await page.mouse.down({ button: "right" });
  await page.mouse.move(panBox.x + panBox.width / 2 + 60, panBox.y + panBox.height / 2 + 30, { steps: 6 });
  await page.mouse.up({ button: "right" });
  await page.evaluate(() => new Promise((done) => requestAnimationFrame(() => requestAnimationFrame(done))));
  const authoritativeCamera = [
    Number(await battlefield.getAttribute("data-camera-pan-x")),
    Number(await battlefield.getAttribute("data-camera-pan-y")),
    Number(await battlefield.getAttribute("data-camera-zoom")),
  ];
  const presentedCamera = (await battlefield.getAttribute("data-presentation-camera")).split(":").map(Number);
  expect(presentedCamera).toEqual(authoritativeCamera);
  expect(Number(await app.getAttribute("data-app-view-constructions"))).toBe(constructionsBeforePan);

  for (let step = 0; step < 20 && await battlefield.getAttribute("data-semantic-tier") !== "overview"; step += 1) {
    await page.mouse.wheel(0, 240);
  }
  await expect(battlefield).toHaveAttribute("data-semantic-tier", "overview");
  const unitGeometryAtOverview = Number(await battlefield.locator("#persistent-layer-units").getAttribute("data-geometry-constructions"));
  const overviewUnit = battlefield.locator("#persistent-layer-units [data-unit-id]").first();
  await expect(overviewUnit).toHaveAttribute("data-unit-class", "rifleman");
  await expect(overviewUnit.locator(".semantic-unit-detail")).toHaveCSS("display", "none");

  for (let step = 0; step < 20 && await battlefield.getAttribute("data-semantic-tier") === "overview"; step += 1) {
    await page.mouse.wheel(0, -120);
  }
  await expect(battlefield).toHaveAttribute("data-semantic-tier", "tactical");
  await expect.poll(async () => Number(await battlefield.locator("#persistent-layer-units").getAttribute("data-geometry-constructions"))).toBeGreaterThan(unitGeometryAtOverview);
  await page.evaluate(() => new Promise((done) => requestAnimationFrame(() => requestAnimationFrame(done))));
  const visibleTacticalUnitId = await battlefield.locator("#persistent-layer-units [data-unit-id]").evaluateAll((nodes, rootBox) => {
    const rootRight = rootBox.x + rootBox.width;
    const rootBottom = rootBox.y + rootBox.height;
    const visible = nodes.find((node) => {
      const bounds = node.getBoundingClientRect();
      return bounds.width > 0 && bounds.height > 0
        && bounds.right > rootBox.x && bounds.left < rootRight
        && bounds.bottom > rootBox.y && bounds.top < rootBottom;
    });
    return visible?.getAttribute("data-unit-id") ?? null;
  }, await battlefield.boundingBox());
  expect(visibleTacticalUnitId).not.toBeNull();
  const tacticalUnit = battlefield.locator(`#persistent-layer-units [data-unit-id="${visibleTacticalUnitId}"]`);
  const terrainConstructionsBeforeSelection = await battlefield.locator("#persistent-layer-terrain").getAttribute("data-layer-constructions");
  const projectionConstructionsBeforeSelection = await battlefield.getAttribute("data-editor-projection-constructions");
  const toolbarConstructionsBeforeSelection = await page.locator(".tactical-compact-toolbar").getAttribute("data-toolbar-constructions");
  const timelineConstructionsBeforeSelection = await page.getByLabel("Unified tactical timeline").getAttribute("data-timeline-constructions");
  const unitGeometryBeforeSelection = await battlefield.locator("#persistent-layer-units").getAttribute("data-geometry-constructions");
  await expect(tacticalUnit).toHaveAttribute("data-unit-class", "rifleman");
  await tacticalUnit.focus();
  await page.keyboard.press("Shift+Enter");
  await expect(tacticalUnit).toHaveAttribute("data-semantic-selected", "true");
  await expect(battlefield.locator("#persistent-layer-terrain")).toHaveAttribute("data-layer-constructions", terrainConstructionsBeforeSelection);
  await expect(battlefield).toHaveAttribute("data-editor-projection-constructions", projectionConstructionsBeforeSelection);
  console.log("toolbar comparator fields", await page.locator(".tactical-compact-toolbar").getAttribute("data-toolbar-comparator-changed-fields"));
  await expect(page.locator(".tactical-compact-toolbar")).toHaveAttribute("data-toolbar-constructions", toolbarConstructionsBeforeSelection);
  await expect(page.getByLabel("Unified tactical timeline")).toHaveAttribute("data-timeline-constructions", timelineConstructionsBeforeSelection);
  await expect(battlefield.locator("#persistent-layer-units")).toHaveAttribute("data-geometry-constructions", unitGeometryBeforeSelection);
  await expect(tacticalUnit.locator(".semantic-unit-detail")).toHaveCSS("display", "inline");
  await expect(battlefield.locator("desc")).toContainText(/Selected unit|Selected disclosed unit/);
});

test("View analysis overlays share pointer and keyboard commands and restore independently", async ({ page }) => {
  await page.goto("/");
  const battlefield = page.locator("#persistent-tactical-svg");
  await expect(battlefield).toHaveAttribute("data-overlay-registry-traversals", "1");
  await expect(battlefield).toHaveAttribute("data-overlay-disclosure-passes", "1");

  await page.getByRole("button", { name: "View", exact: true }).click();
  const exactLos = page.getByRole("menuitemcheckbox", { name: /Exact line of sight/ });
  await expect(exactLos).toHaveAttribute("aria-checked", "false");
  await exactLos.dispatchEvent("pointerdown", { pointerId: 7, pointerType: "mouse", isPrimary: true });
  await expect(exactLos).toHaveAttribute("aria-checked", "true");
  await expect(exactLos).toHaveAttribute("data-overlay-mode", "InspectHeld");
  await exactLos.dispatchEvent("pointerup", { pointerId: 7, pointerType: "mouse", isPrimary: true });
  await expect(exactLos).toHaveAttribute("aria-checked", "false");
  await exactLos.click();
  await expect(battlefield).toHaveAttribute("data-overlay-preferences", /spatial\.exact-los=selection/);

  await page.reload();
  await expect(battlefield).toHaveAttribute("data-overlay-preferences", /spatial\.exact-los=selection/);
  const projectionConstructionsBeforeOverlay = await battlefield.getAttribute("data-editor-projection-constructions");
  const timelineConstructionsBeforeOverlay = await page.getByLabel("Unified tactical timeline").getAttribute("data-timeline-constructions");
  await page.keyboard.press("Alt+l");
  await expect(battlefield).toHaveAttribute("data-overlay-preferences", /spatial\.exact-los=off/);
  await expect(battlefield).toHaveAttribute("data-editor-projection-constructions", projectionConstructionsBeforeOverlay);
  await expect(page.getByLabel("Unified tactical timeline")).toHaveAttribute("data-timeline-constructions", timelineConstructionsBeforeOverlay);

  const footprint = battlefield.locator('[data-overlay-id="unit.footprints"] rect').first();
  await expect(footprint).toBeVisible();
  await expect(footprint).toHaveCSS("vector-effect", "non-scaling-stroke");
  const normalStroke = await footprint.evaluate((node) => getComputedStyle(node).strokeWidth);
  expect(normalStroke).toBe("2px");
  await page.emulateMedia({ forcedColors: "active" });
  await expect.poll(() => footprint.evaluate((node) => getComputedStyle(node).strokeWidth)).toBe("3px");
  await page.evaluate(() => { document.documentElement.style.zoom = "4"; });
  await page.getByRole("button", { name: "View", exact: true }).click();
  await expect(page.getByRole("menuitemcheckbox", { name: /Unit footprints/ })).toBeVisible();
  const overlayLayer = battlefield.locator("#persistent-tactical-overlay-layer");
  const overlayNodeEstimate = Number(await battlefield.getAttribute("data-overlay-node-estimate"));
  const actualOverlayNodes = await overlayLayer.locator("*").count();
  expect(actualOverlayNodes).toBe(overlayNodeEstimate);
  expect(actualOverlayNodes).toBeLessThanOrEqual(5000);
  const footprintBox = await footprint.boundingBox();
  expect(footprintBox?.width).toBeGreaterThan(20);
  expect(footprintBox?.height).toBeGreaterThan(20);
  await expect(overlayLayer).toHaveAttribute("data-overlay-patterns", "non-color-only");
});

test("the player-visible Rules explorer renders the executable combat corpus and pinned source", async ({ page }) => {
  let physicalAuthorityRequests = 0;
  page.on("request", (request) => {
    if (request.url().includes("/api/combat/physical-drill")) physicalAuthorityRequests += 1;
  });
  await page.goto("/");
  await page.getByRole("button", { name: "View", exact: true }).click();
  await page.getByRole("menuitem", { name: /Rules data/ }).click();
  const explorer = page.getByRole("region", { name: "Rules data tables", exact: true });
  await expect(explorer).toBeVisible();
  await expect(explorer.getByRole("heading", { name: /FS\.GG\.Game\.Core@0\.13\.0/ })).toBeVisible();
  await expect(explorer.getByRole("heading", { name: /AttackResolved event/ })).toHaveCount(0);
  await explorer.getByRole("button", { name: "Execute canonical player attack" }).click();
  await expect(explorer.getByRole("heading", { name: "AttackResolved event tick-1-attack-10-20" })).toBeVisible();
  await expect(explorer.getByText(/Damage 25 · remaining health 75/)).toBeVisible();
  await expect(explorer.getByText(/COMBAT-DAMAGE-001.*baseDamage=.*trace=.*retention=.*→.*damage/)).toBeVisible();
  await explorer.getByRole("link", { name: "Open governing rule COMBAT-ATTACK-RESOLUTION-001" }).click();
  await expect(page).toHaveURL(/#rule-COMBAT-ATTACK-RESOLUTION-001$/);
  await expect(explorer.getByText("Transition · AttackPhase · events AttackResolved, CoverDestroyed", { exact: true })).toBeVisible();
  const damage = explorer.getByText(/^COMBAT-DAMAGE-001 · Expected damage$/);
  await damage.click();
  const damageRule = damage.locator("..");
  await expect(explorer.getByText(/baseDamage:damage.*trace:ratio.*retention:ratio/)).toBeVisible();
  const source = explorer.getByRole("link", { name: /Pinned F# source · CombatRules.damage/ });
  if (process.env.SIR_RULES_EXPLORER_MUTATE_SUBJECT === "source") {
    await source.evaluate((node) => node.setAttribute("href", "https://example.invalid/mutated-source"));
  }
  await expect(source).toHaveAttribute(
    "href",
    `https://github.com/EHotwagner/S.I.R./blob/${rulesImplementationSources.sourceCommit}/src/SIR.Simulation/CombatRules.fs`,
  );
  await expect(damageRule.getByText(/examples: tests\/SIR\.Conformance\.Shared\/RulesCorpusFixtures\.fs · properties:/)).toBeVisible();
  await expect(damageRule.getByRole("link", { name: "Coverage graph" })).toHaveAttribute("href", /rules-corpus\/v2\/coverage\.json/);

  const drill = explorer.getByRole("region", { name: "Physical combat drill", exact: true });
  await expect(drill.getByRole("button", { name: "Run four-profile combat scenario" })).toBeEnabled();
  const authorityResponse = page.waitForResponse((response) => response.url().includes("/api/combat/physical-drill") && response.status() === 200);
  await drill.getByRole("button", { name: "Run four-profile combat scenario" }).click();
  const response = await authorityResponse;
  const responseBody = await response.text();
  expect(physicalAuthorityRequests).toBe(1);
  await expect(drill.getByText("Cover integrity 50 → 0 · destroyed true", { exact: true })).toBeVisible();
  if (process.env.SIR_RULES_EXPLORER_MUTATE_SUBJECT === "replay") {
    await drill.getByText(/Replay v6 verified true/).evaluate((node) => { node.textContent = node.textContent.replace("Replay v6", "Replay v5"); });
  }
  await expect(drill.getByText(/Replay v6 verified true from 4 seek points · final tick 4 · state [0-9a-f]{64}/)).toBeVisible();

  const expectedProfiles = [
    ["Rifle", "50 → 38 · destroyed false"],
    ["SupportWeapon", "38 → 38 · destroyed false"],
    ["AntiArmor", "38 → 13 · destroyed false"],
    ["LobbedArea", "13 → 0 · destroyed true"],
  ];
  for (const [profile, coverIntegrity] of expectedProfiles) {
    const outcome = drill.getByRole("article", { name: `${profile} authoritative outcome`, exact: true });
    await expect(outcome).toBeVisible();
    await expect(outcome.getByRole("heading", { name: profile, exact: true })).toBeVisible();
    await expect(outcome.getByLabel(`${profile} visible attack trace`, { exact: true })).toBeVisible();
    await expect(outcome.getByText(coverIntegrity, { exact: true })).toBeVisible();
    await expect(outcome.getByRole("list")).toContainText("HP");
    await expect(outcome.getByRole("list")).toContainText("Suppression");
  }
  const antiArmor = drill.getByRole("article", { name: "AntiArmor authoritative outcome", exact: true });
  await expect(antiArmor.getByText(/roadblock-2 · retained 50%/)).toBeVisible();
  await expect(antiArmor.getByText(/Front rating 50 vs penetration 70 · retained 100%/)).toBeVisible();
  await expect(antiArmor.getByText("67 / Serious", { exact: true })).toBeVisible();
  const antiArmorExplanation = antiArmor.getByRole("list");
  await expect(antiArmorExplanation).toContainText("Physical trace");
  await expect(antiArmorExplanation).toContainText("Cover");
  await expect(antiArmorExplanation).toContainText("Armor");
  await expect(antiArmorExplanation).toContainText("Wound");
  console.log(JSON.stringify({ schema: "sir-physical-combat-route-v1", authorityRequests: physicalAuthorityRequests, responseBytes: Buffer.byteLength(responseBody, "utf8") }));
});

test("the production browser consumes only the observer-local awareness and reaction projection", async ({ page }) => {
  let authorityRequests = 0;
  page.on("request", (request) => {
    if (request.url().includes("/api/awareness/local-projection")) authorityRequests += 1;
  });
  await page.goto("/");
  await page.getByRole("button", { name: "View", exact: true }).click();
  await page.getByRole("menuitem", { name: /Rules data/ }).click();
  const projection = page.getByRole("region", { name: "Local awareness and reaction projection", exact: true });
  const act = async (name) => {
    const responsePromise = page.waitForResponse((response) => response.url().includes("/api/awareness/local-projection") && response.status() === 200);
    await projection.getByRole("button", { name }).click();
    return responsePromise;
  };
  await act("Reset awareness drill");
  await act("Rotate attention east");
  await act("Prepare covered sector");
  await act("Complete preparation");
  const response = await act("Move opposing unit through coverage");
  let body = await response.text();
  if (process.env.SIR_AWARENESS_BROWSER_MUTATE_SUBJECT === "projection") {
    const mutated = JSON.parse(body);
    mutated.Contacts = [];
    body = JSON.stringify(mutated);
  }
  const responseSubject = JSON.parse(body);
  expect(authorityRequests).toBe(5);
  expect(body).not.toContain("Units");
  expect(body).not.toContain("Board");
  expect(body).not.toContain("SpatialEvidence");
  expect(responseSubject.Contacts).toHaveLength(1);
  expect(responseSubject.Stimuli).toHaveLength(1);
  await expect(projection.getByText(/Observer 10 · tick 5 · contacts 1 · candidate pairs 2 · LOS 2/)).toBeVisible();
  await expect(projection.getByRole("heading", { name: "Contact 20 · Acquired" })).toBeVisible();
  await expect(projection.getByText(/Engagement player-area-east · area:2,0 · attention East · posture Prepared · Resolved · ResolvedByPhysicalAuthority/)).toBeVisible();
  await expect(projection.getByText("Authoritative order committed:10:20:player-area-east → physical:10 → resolved:10:20:player-area-east", { exact: true })).toBeVisible();
  await act("Scrub awareness timeline to start");
  await expect(projection.getByText(/Observer 10 · tick 1/)).toBeVisible();
  await act("Scrub awareness timeline to reaction");
  await expect(projection.getByText(/Observer 10 · tick 5/)).toBeVisible();
  expect(authorityRequests).toBe(7);
  console.log(JSON.stringify({ schema: "sir-local-awareness-browser-v1", authorityRequests, responseBytes: Buffer.byteLength(body, "utf8") }));
});

test("the player-visible spatial diagnostics route shows authoritative selected-unit evidence", async ({ page }) => {
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  await battlefield.locator("#persistent-layer-units [data-unit-id]").first().click();
  await page.getByRole("button", { name: "View", exact: true }).click();
  await page.getByRole("menuitem", { name: /Spatial diagnostics/ }).click();
  const diagnostics = page.getByRole("region", { name: "Selected unit spatial diagnostics", exact: true });
  await expect(diagnostics).toBeVisible();
  await expect(diagnostics.getByText(/ExactLineOfSight · Found/)).toBeVisible();
  await expect(diagnostics.getByText(/BoundedPath · Found/)).toBeVisible();
  await expect(diagnostics.getByText(/Cover · Found/)).toBeVisible();
  await expect(diagnostics.getByText("Normalized inputs", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Footprint samples", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Authoritative path", { exact: true }).first()).toBeVisible();
  const boundedPath = diagnostics.locator("details").filter({ hasText: "BoundedPath · Found" });
  const renderedPath = boundedPath.getByText("Authoritative path", { exact: true }).locator("+ dd");
  await expect(renderedPath).not.toHaveText("none");
  await expect(renderedPath).toHaveText(/^\(\d+,\d+\)(?:, \(\d+,\d+\))+$/);
  await expect(diagnostics.getByText("Crossed cells", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Crossed edges", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Cover contributors", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Decisions", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText("Expansion / truncation", { exact: true }).first()).toBeVisible();
  await expect(diagnostics.getByText(/player-disclosed/).first()).toBeVisible();
  await expect(diagnostics.getByText(/FS\.GG\.Game\.Core@0\.13\.0.*fs-gg-game-core-fable-lockstep-v1/).first()).toBeVisible();
  await expect(diagnostics.getByText("SIR.Simulation.SpatialQuery.evaluate", { exact: true }).first()).toBeVisible();
});

test("the maintained simulation transport is available without a manual handoff in every modality", async ({ page }) => {
  await loadMaintainedSimulation(page);
  for (const mode of ["Editor", "Plan", "Simulate", "Review"]) {
    await switchWorkspace(page, mode);
    await page.getByRole("button", { name: "Simulation", exact: true }).click();
    await expect(page.getByRole("menu", { name: "Simulation commands" }).getByRole("menuitem", { name: /^Play or pause/ })).toBeEnabled();
    await page.keyboard.press("Escape");
  }
  await expect(page.getByText(/simulator handoff/i)).toHaveCount(0);
});

test("maintained runtime state is truthful at the cursor in every modality", async ({ page }) => {
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  const unit = battlefield.locator("#persistent-layer-units [data-unit-id]").first();
  await unit.click();
  await page.locator("#unit-controller").selectOption({ label: "Scripted AI" });
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  const runtimeUnits = await observableUnitState(battlefield);
  expect(runtimeUnits[0].status).toContain("scripted");
  for (const mode of ["Simulate", "Editor", "Plan", "Review"]) {
    await switchWorkspace(page, mode);
    const expectedOwner = mode === "Simulate" ? "SimulatorScene" : mode === "Plan" ? "PlanningScene" : "EditorScene";
    await expect(battlefield).toHaveAttribute("data-scene-owner", expectedOwner);
    await expect(battlefield).toHaveAttribute("data-scene-tick", "1");
    await expect(page.getByLabel("Unified tactical timeline")).toHaveAttribute("data-time-cursor", "1");
    expect(await observableUnitState(battlefield)).toEqual(runtimeUnits);
  }
});

test("advance pause place seek activation and resume preserve continuous state", async ({ page }) => {
  await loadMaintainedSimulation(page);
  await page.getByRole("button", { name: "View", exact: true }).click();
  await page.getByRole("menu", { name: "View commands" }).getByRole("menuitemcheckbox", { name: "Timeline", exact: true }).click();
  const battlefield = page.locator("#persistent-tactical-svg");
  const play = page.getByRole("button", { name: "Play tactical timeline", exact: true });
  const pause = page.getByRole("button", { name: "Pause tactical timeline", exact: true });
  await play.click();
  await expect(pause).toBeVisible();
  await expect.poll(async () => Number(await battlefield.getAttribute("data-scene-tick"))).toBeGreaterThan(0);
  await pause.click();
  await expect(play).toBeVisible();
  const activationTick = Number(await battlefield.getAttribute("data-scene-tick"));
  await page.waitForTimeout(250);
  await expect(battlefield).toHaveAttribute("data-scene-tick", String(activationTick));
  const originalUnitCount = await battlefield.locator("#persistent-layer-units [data-unit-id]").count();
  const existingBefore = await observableUnitState(battlefield);
  const existingIds = existingBefore.map((unit) => unit.id);

  await switchWorkspace(page, "Editor");
  const tools = await expandPanel(page, "tools");
  await tools.getByRole("button", { name: "Units", exact: true }).click();
  await tools.locator(".unit-preset-group button").first().click();
  await battlefield.locator('[aria-label="Activate cell 12,4"]').click();
  await switchWorkspace(page, "Simulate");
  await expect(page.getByText(`Added 1 unit(s) at tick ${activationTick}.`, { exact: true })).toBeVisible();
  await expect(battlefield.locator("#persistent-layer-units [data-unit-id]")).toHaveCount(originalUnitCount + 1);
  expect(await observableUnitState(battlefield, existingIds)).toEqual(existingBefore);
  const liveActivationState = await battlefield.locator("#persistent-layer-units").innerHTML();

  await page.getByRole("button", { name: "Go to tactical timeline start", exact: true }).click();
  await expect(battlefield).toHaveAttribute("data-scene-tick", "0");
  await expect(battlefield.locator("#persistent-layer-units [data-unit-id]")).toHaveCount(originalUnitCount);
  const slider = page.getByRole("slider", { name: "Current tactical time", exact: true });
  if (activationTick > 1) {
    await slider.fill(String(activationTick - 1));
    await expect(battlefield).toHaveAttribute("data-scene-tick", String(activationTick - 1));
    await expect(battlefield.locator("#persistent-layer-units [data-unit-id]")).toHaveCount(originalUnitCount);
  }
  await page.getByRole("button", { name: "Step tactical timeline forward", exact: true }).click();
  await expect(battlefield).toHaveAttribute("data-scene-tick", String(activationTick));
  await expect(battlefield.locator("#persistent-layer-units")).toHaveJSProperty("innerHTML", liveActivationState);

  await play.click();
  await expect(pause).toBeVisible();
  await expect.poll(async () => Number(await battlefield.getAttribute("data-scene-tick"))).toBeGreaterThan(activationTick);
  await pause.click();
  await expect(play).toBeVisible();
  const finalPausedTick = await battlefield.getAttribute("data-scene-tick");
  await page.waitForTimeout(250);
  await expect(battlefield).toHaveAttribute("data-scene-tick", finalPausedTick);
});

test("terrain edits reset with a terrain-specific visible explanation", async ({ page }) => {
  await loadMaintainedSimulation(page);
  const battlefield = page.locator("#persistent-tactical-svg");
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await switchWorkspace(page, "Editor");
  const tools = await expandPanel(page, "tools");
  await tools.getByRole("button", { name: "Terrain", exact: true }).click();
  await tools.getByRole("button", { name: "Pencil", exact: true }).click();
  await tools.getByRole("button", { name: /^rough terrain,/i }).click();
  await battlefield.focus();
  await battlefield.press("Enter");
  await tools.getByRole("button", { name: /^blocked terrain,/i }).click();
  await battlefield.focus();
  await battlefield.press("Enter");
  await switchWorkspace(page, "Simulate");
  await expect(page.getByText("Simulation restarted at tick 0 because terrain changed.", { exact: true })).toBeVisible();
});

test("topology edits reset with a topology-specific visible explanation", async ({ page }) => {
  await loadMaintainedSimulation(page);
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await switchWorkspace(page, "Editor");
  const edgeTools = await expandPanel(page, "tools");
  await edgeTools.getByRole("button", { name: "Edges", exact: true }).click();
  await edgeTools.getByRole("button", { name: "Convert cursor edge to wall", exact: true }).click();
  await edgeTools.getByRole("button", { name: "Convert cursor edge to a window", exact: true }).click();
  await switchWorkspace(page, "Simulate");
  await expect(page.getByText("Simulation restarted at tick 0 because edge topology changed.", { exact: true })).toBeVisible();
});

test("the normal UI remains operable at 400 percent browser zoom", async ({ page }) => {
  await page.goto("/");
  // Browser-zoom environment model: quarter the CSS viewport and raise DPR to
  // four, which exercises the same responsive media queries as 400% zoom.
  const cdp = await page.context().newCDPSession(page);
  await cdp.send("Emulation.setDeviceMetricsOverride", {
    width: 320,
    height: 180,
    deviceScaleFactor: 4,
    mobile: false,
  });
  await expect.poll(() => page.evaluate(() => window.innerWidth)).toBeLessThanOrEqual(320);
  await expect.poll(() => page.evaluate(() => window.devicePixelRatio)).toBeGreaterThanOrEqual(4);
  await expect(page.getByRole("main", { name: "S.I.R. simulator and editor" })).toBeVisible();
  await switchWorkspace(page, "Simulate");
  await openSamples(page);
  const samplesOwner = page.getByLabel("Curated samples feature", { exact: true });
  await expect(samplesOwner).toBeVisible();
  await expect(samplesOwner.getByRole("region", { name: "Curated maps simulations and replays", exact: true })).toBeVisible();
});

test("a valid map selected through the visible import control reports success", async ({ page }) => {
  await page.goto("/");
  await switchWorkspace(page, "Editor");
  await page.getByRole("button", { name: "Expand Document / revision panel", exact: true }).click();
  const picker = page.getByLabel("Import SIR map", { exact: true });
  await expect(picker).toBeVisible();
  await picker.setInputFiles({
    name: "invalid.sir-map",
    mimeType: "text/plain",
    buffer: Buffer.from("not a SIR map"),
  });
  await expect(page.getByRole("alert")).toContainText(/not a supported|Map line/i);
  await picker.setInputFiles({
    name: "visible-success.sir-map",
    mimeType: "text/plain",
    buffer: Buffer.from("SIR-MAP 2\nsize 4 4\n"),
  });
  await expect(page.getByRole("alert")).toContainText("Imported map visible-success.sir-map.");
});

test("the visible replay picker rejects corruption then loads the engine-bound retained package", async ({ page }) => {
  await page.goto("/");
  await switchWorkspace(page, "Review");
  const picker = page.getByLabel("Choose replay package", { exact: true });
  await expect(picker).toBeVisible();
  const corrupt = Buffer.from(retainedReplay);
  corrupt[corrupt.length - 1] ^= 0x01;
  await picker.setInputFiles({ name: "corrupt.sirr", mimeType: "application/octet-stream", buffer: corrupt });
  await expect(page.getByText(/corrupt\.sirr rejected:/)).toBeVisible();
  await picker.setInputFiles({ name: "retained.sirr", mimeType: "application/octet-stream", buffer: retainedReplay });
  await expect(page.getByText(/Loaded retained\.sirr/)).toBeVisible();
});

test("the visible background picker rejects an oversized file then reports attachment", async ({ page }) => {
  await page.goto("/");
  await switchWorkspace(page, "Editor");
  await page.getByRole("button", { name: "Expand Document / revision panel", exact: true }).click();
  const picker = page.getByLabel("Choose local raster map background", { exact: true });
  await expect(picker).toBeVisible();
  await picker.setInputFiles({ name: "too-large.png", mimeType: "image/png", buffer: Buffer.alloc(10_485_761) });
  await expect(page.getByRole("alert")).toContainText(/allowed maximum/i);
  await picker.setInputFiles({
    name: "attached.png",
    mimeType: "image/png",
    buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL9bQAAAABJRU5ErkJggg==", "base64"),
  });
  await expect(page.getByRole("alert")).toContainText("Attached background attached.png.");
});

test("a curated sample exposes maintained playback and can reset", async ({ page }) => {
  await loadMaintainedSimulation(page);

  const runtimeTick = page.getByText(/Authoritative runtime tick \d+/);
  await page.getByRole("button", { name: "Simulation", exact: true }).click();
  await page.getByRole("menu", { name: "Simulation commands" }).getByRole("menuitem", { name: /^Play or pause/ }).click();
  await expect(runtimeTick).not.toHaveText(/^Authoritative runtime tick 0\b/);
  await page.getByRole("button", { name: "Simulation", exact: true }).click();
  await page.getByRole("menu", { name: "Simulation commands" }).getByRole("menuitem", { name: /^Play or pause/ }).click();
  const beforeTick = Number((await runtimeTick.textContent()).match(/\d+/)[0]);
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await expect(runtimeTick).toHaveText(new RegExp(`^Authoritative runtime tick ${beforeTick + 1}\\b`));
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "Reset simulation to the current authored baseline", exact: true }).filter({ hasText: "Reset simulation" }).click();
  await expect(page.getByText(/Authoritative runtime tick 0/)).toBeVisible();
});

test("production simulator status exposes continuous runtime time without handoff chrome", async ({ page }) => {
  await loadMaintainedSimulation(page);
  await expect(page.getByText(/^Authoritative runtime tick 0/)).toBeVisible();
  await expect(page.getByText(/manual.*handoff/i)).toHaveCount(0);
  await page.getByRole("button", { name: "Advance the map simulation one tick", exact: true }).click();
  await expect(page.getByText(/^Authoritative runtime tick 1/)).toBeVisible();
});

test("live authority reconnect remains visible through the production command surface", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Simulation", exact: true }).click();
  await expect(page.getByRole("menu", { name: "Simulation commands" })).toBeVisible();
  const live = page.getByRole("region", { name: "Authoritative live session" });
  await expect(live).toContainText("live connected", { timeout: 90_000 });
  await page.getByRole("menuitem", { name: "Send the next player-visible live advance command" }).click();
  await expect(live).toContainText(/tick [1-9]/, { timeout: 30_000 });
  await page.getByRole("menuitem", { name: "Disconnect the player-visible live session" }).click();
  await expect(live).toContainText("live disconnected");
  await page.getByRole("menuitem", { name: "Reconnect and request the authoritative live snapshot" }).click();
  await expect(live).toContainText("live connected");
});
