<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ScenarioCatalogRuntime.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SIR.Replay.Core/SIR.Replay.Core.fsproj" />
  </ItemGroup>
</Project>
