// <auto-generated>
// Generated by scripts/generate-control-abi.mjs from docs/control-abi-v1.json.
// </auto-generated>
namespace SIR.ControlAbi

[<RequireQualifiedAccess>]
module V1Constants =
    [<Literal>]
    let Major = 1uy
    [<Literal>]
    let Minor = 0uy
    [<Literal>]
    let HeaderBytes = 32
    [<Literal>]
    let SectionHeaderBytes = 12
    [<Literal>]
    let InputMaximumBytes = 65536
    [<Literal>]
    let OutputMaximumBytes = 16384
    [<Literal>]
    let MaximumSections = 32
    [<Literal>]
    let MaximumElementsPerSection = 256
    [<Literal>]
    let MaximumStringBytes = 255
    [<Literal>]
    let MaximumOpaquePayloadBytes = 4096
    [<Literal>]
    let RequiredSectionFlag = 0x0001us
    [<Literal>]
    let OwnStateTag = 0x0001us
    [<Literal>]
    let ResolvedOrientationTag = 0x0002us
    [<Literal>]
    let ActionAndRecoveryTag = 0x0003us
    [<Literal>]
    let ObservationsAndStimuliTag = 0x0004us
    [<Literal>]
    let EventsTag = 0x0005us
    [<Literal>]
    let MessagesAndReportsTag = 0x0006us
    [<Literal>]
    let CapabilityDescriptorsTag = 0x0007us
    [<Literal>]
    let ServiceResultsTag = 0x0008us
    [<Literal>]
    let RequestStatusTag = 0x0009us
    [<Literal>]
    let OutputRequestsTag = 0x1001us

[<RequireQualifiedAccess>]
type RequestKind =
    | SetMovementIntent = 1
    | SetFacing = 2
    | SetAttention = 3
    | SetStance = 4
    | SetEngagement = 5
    | StartCapability = 6
    | CancelAction = 7
    | SendMessage = 8
    | RequestService = 9
    | SetEmissionPolicy = 10
    | SetFormationIntent = 11
    | Sleep = 12

[<RequireQualifiedAccess>]
type DirectionCode =
    | North = 0
    | NorthEast = 1
    | East = 2
    | SouthEast = 3
    | South = 4
    | SouthWest = 5
    | West = 6
    | NorthWest = 7

[<RequireQualifiedAccess>]
type TargetKind =
    | KnownUnit = 1
    | Cell = 2
    | Area = 3
    | Edge = 4
    | Referent = 5

[<RequireQualifiedAccess>]
type MovementPosture =
    | Balanced = 0
    | Speed = 1
    | Readiness = 2

[<RequireQualifiedAccess>]
type EmissionPolicy =
    | Free = 0
    | Restricted = 1
    | Silent = 2

[<RequireQualifiedAccess>]
type FormationOperation =
    | AdoptStation = 1
    | RequestTemplate = 2
    | Release = 3

[<RequireQualifiedAccess>]
type EngagementOperation =
    | Declare = 1
    | Disengage = 2

[<RequireQualifiedAccess>]
type ServiceKind =
    | PathSearch = 1

[<RequireQualifiedAccess>]
type EventKind =
    | ContactGained = 1
    | ContactUpdated = 2
    | ContactLost = 3
    | StimulusReceived = 4
    | DamageTaken = 5
    | WoundSustained = 6
    | SuppressionChanged = 7
    | HealthStateChanged = 8
    | StrainChanged = 9
    | ActionCompleted = 10
    | ActionFailed = 11
    | ActionInterrupted = 12
    | EngagementSolutionLost = 13
    | ServiceResult = 14
    | MessageReceived = 15
    | OrderReceived = 16
    | CommandRoleChanged = 17
    | ConnectivityChanged = 18
    | InterferenceDetected = 19
    | ReportDelivered = 20
    | ReferentDesignated = 21
    | ReferentInvalidated = 22
    | ObjectiveStateChanged = 23
    | TerrainChanged = 24
    | FormationStationChanged = 25
    | InventoryChanged = 26
    | TransferOutcome = 27
    | SupplyObserved = 28

[<RequireQualifiedAccess>]
type ModuleStatus =
    | MalformedInput = -1
    | UnsupportedVersion = -2
    | InputTooLarge = -3
    | OutputCapacityInsufficient = -4
    | ConfigurationInvalid = -5
    | InternalFault = -6

[<RequireQualifiedAccess>]
type InvocationFailure =
    | None = 0
    | ModuleRejectedInput = 1
    | ModuleTrapped = 2
    | FuelExhausted = 3
    | InvalidOutputLength = 4
    | MalformedOutput = 5
    | ForbiddenRequest = 6
    | MemoryLimitExceeded = 7
    | HostServiceLimitExceeded = 8

[<RequireQualifiedAccess>]
type RequestFailure =
    | None = 0
    | MalformedRequest = 1
    | UnknownRequestKind = 2
    | DuplicateRequestId = 3
    | RequestLimitExceeded = 4
    | InvalidDirection = 5
    | InvalidTarget = 6
    | KnowledgeUnavailable = 7
    | CapabilityUnavailable = 8
    | ActionNotPermitted = 9
    | ResourceUnavailable = 10
    | ServiceUnavailable = 11
    | MessageNotPermitted = 12
    | FormationUnavailable = 13
    | InvalidWakeTick = 14
    | Superseded = 15

[<RequireQualifiedAccess>]
type ActionFailure =
    | None = 0
    | Cancelled = 1
    | Interrupted = 2
    | TargetLost = 3
    | OutOfRange = 4
    | LineBlocked = 5
    | CapabilityUnavailable = 6
    | ResourceUnavailable = 7
    | TargetInvalidated = 8
    | ServiceFailed = 9
    | FormationBroken = 10
    | DeadlineExpired = 11
    | Superseded = 12
