<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Worker.fs" />
    <Compile Include="Runner.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SIR.Client/SIR.Client.fsproj" />
    <ProjectReference Include="../SIR.Simulation/SIR.Simulation.fsproj" />
    <PackageReference Include="Fable.Browser.Dom" />
    <PackageReference Include="Fable.Elmish" />
    <PackageReference Include="Fable.Elmish.React" />
    <PackageReference Include="Feliz" />
  </ItemGroup>
</Project>
