<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="SpatialServices.fs" />
    <Compile Include="PhysicalCombatServices.fs" />
    <Compile Include="LiveIntegration.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SIR.Domain/SIR.Domain.fsproj" />
    <ProjectReference Include="../SIR.Simulation/SIR.Simulation.fsproj" />
    <ProjectReference Include="../SIR.Wasm/SIR.Wasm.fsproj" />
  </ItemGroup>
</Project>
