
import { singleton } from "./fable_modules/fable-library-js.5.13.0/Set.js";
import { stringHash, comparePrimitives, equals, int32ToString, compare } from "./fable_modules/fable-library-js.5.13.0/Util.js";
import { TacticalModality, UnifiedTacticalWorkspace_modalCommandDefinitions, UnifiedTacticalWorkspace_commandRegistry, TacticalCommandDefinition, TacticalCommandAvailability } from "./SIR.Client/UnifiedTacticalWorkspace.js";
import { List_distinctBy } from "./fable_modules/fable-library-js.5.13.0/Seq2.js";
import { cons, singleton as singleton_1, map as map_1, ofArray, empty, append } from "./fable_modules/fable-library-js.5.13.0/List.js";
import { ModalInput_simulatorCatalog, EditorModalFacts, ModalInput_editorCatalog } from "./SIR.Client/ModalInput.js";
import { EditorDomain } from "./SIR.Client/MapEditorTypes.js";
import { editorPanHeld } from "./AppShell.js";
import { singleton as singleton_2, map as map_2, collect, append as append_1, delay, toList } from "./fable_modules/fable-library-js.5.13.0/Seq.js";
import { mapIndexed, map } from "./fable_modules/fable-library-js.5.13.0/Array.js";
import { rangeDouble } from "./fable_modules/fable-library-js.5.13.0/Range.js";
import { PlanningTool } from "./SIR.Client/PlanningWorkspace.js";
import { empty as empty_1, toList as toList_1 } from "./fable_modules/fable-library-js.5.13.0/Map.js";
import { defaultArg } from "./fable_modules/fable-library-js.5.13.0/Option.js";

export function activeTacticalRegistry(model) {
    let matchValue, matchValue_1, matchValue_2, matchValue_3, planning, selectionActions, battlefieldActions, matchValue_5, selectionActions_1, option_1, controllerActions;
    const pointerCommand = (id, label, category, modality) => (new TacticalCommandDefinition(id, label, category, singleton(modality, {
        Compare: (x, y) => (compare(x, y) | 0),
    }), undefined, true, 300, undefined, undefined, TacticalCommandAvailability.AlwaysAvailable));
    return List_distinctBy((_arg_5) => _arg_5.Id, append(UnifiedTacticalWorkspace_commandRegistry, append((matchValue = model.Workspace, (matchValue.tag === 2) ? UnifiedTacticalWorkspace_modalCommandDefinitions(TacticalModality.Editor, ModalInput_editorCatalog(new EditorModalFacts(model.Editor, (matchValue_1 = model.EditorToolPanel, (matchValue_1.tag === 1) ? EditorDomain.UnitDomain : ((matchValue_1.tag === 2) ? EditorDomain.EdgeDomain : ((matchValue_1.tag === 3) ? EditorDomain.RegionDomain : ((matchValue_1.tag === 4) ? EditorDomain.DocumentDomain : EditorDomain.TerrainDomain)))), editorPanHeld(model), model.InputHelpExpanded))) : ((matchValue.tag === 0) ? UnifiedTacticalWorkspace_modalCommandDefinitions(TacticalModality.Simulate, ModalInput_simulatorCatalog(model.SimulatorSelectedUnit, model.Simulator, model.SimulatorControllerSelection)) : empty())), append((matchValue_2 = model.Workspace, (matchValue_3 = model.Planning, (matchValue_2.tag === 1) ? ((matchValue_3 != null) ? ((planning = matchValue_3, (selectionActions = toList(delay(() => append_1(ofArray(map((unit) => pointerCommand("planning.roster.select." + int32ToString(unit.UnitId), "Select " + unit.Name, "Plan roster", TacticalModality.Plan), planning.Roster)), delay(() => append_1(map_1((command) => pointerCommand("planning.timeline.select." + command.Id, "Select timeline command " + command.Id, "Plan timeline", TacticalModality.Plan), planning.Commands), delay(() => ofArray(mapIndexed((index, issue) => pointerCommand("planning.issue.focus." + int32ToString(index), "Focus issue " + issue.Code, "Plan validation", TacticalModality.Plan), planning.Issues)))))))), (battlefieldActions = toList(delay(() => collect((row_1) => map_2((column_1) => pointerCommand((("planning.battlefield.cell." + int32ToString(column_1)) + ".") + int32ToString(row_1), (("Add route waypoint " + int32ToString(column_1)) + ",") + int32ToString(row_1), "Plan battlefield cells", TacticalModality.Plan), rangeDouble(0, 1, model.Editor.Map.Width - 1)), rangeDouble(0, 1, model.Editor.Map.Height - 1)))), (planning.SelectedUnit == null) ? selectionActions : append(selectionActions, append(battlefieldActions, (matchValue_5 = planning.Tool, (matchValue_5.tag === 1) ? map_1((direction_1) => {
        const channel = equals(planning.Tool, PlanningTool.FacingTool) ? "facing" : "attention";
        return pointerCommand((("planning.inspector." + channel) + ".") + direction_1, (("Set " + channel) + " ") + direction_1, "Plan inspector", TacticalModality.Plan);
    }, ofArray(["north", "north-east", "east", "south-east", "south", "south-west", "west", "north-west"])) : ((matchValue_5.tag === 2) ? map_1((direction_1) => {
        const channel = equals(planning.Tool, PlanningTool.FacingTool) ? "facing" : "attention";
        return pointerCommand((("planning.inspector." + channel) + ".") + direction_1, (("Set " + channel) + " ") + direction_1, "Plan inspector", TacticalModality.Plan);
    }, ofArray(["north", "north-east", "east", "south-east", "south", "south-west", "west", "north-west"])) : ((matchValue_5.tag === 3) ? map_1((stance) => pointerCommand("planning.inspector.stance." + stance, "Set stance " + stance, "Plan inspector", TacticalModality.Plan), ofArray(["standing", "crouched", "prone"])) : ((matchValue_5.tag === 4) ? singleton_1(pointerCommand("planning.inspector.hold", "Add hold", "Plan inspector", TacticalModality.Plan)) : ((matchValue_5.tag === 5) ? singleton_1(pointerCommand("planning.inspector.engagement", "Add disclosed engagement", "Plan inspector", TacticalModality.Plan)) : ((matchValue_5.tag === 6) ? singleton_1(pointerCommand("planning.inspector.synchronization", "Add synchronization marker", "Plan inspector", TacticalModality.Plan)) : map_1((direction) => pointerCommand("planning.inspector.waypoint." + direction, "Add waypoint " + direction, "Plan inspector", TacticalModality.Plan), ofArray(["west", "north", "south", "east"])))))))))))))) : empty()) : ((matchValue_2.tag === 0) ? ((selectionActions_1 = map_1((tupledArg_1) => {
        const unitId_1 = tupledArg_1[0] | 0;
        return pointerCommand("simulator.scene.select.unit." + int32ToString(unitId_1), "Select shared-scene unit " + int32ToString(unitId_1), "Simulator shared scene", TacticalModality.Simulate);
    }, toList_1(defaultArg((option_1 = model.Simulator, (option_1 != null) ? option_1.RuntimeMap.Units : undefined), empty_1({
        Compare: (x_1, y_1) => (comparePrimitives(x_1, y_1) | 0),
    })))), (controllerActions = map_1((tupledArg_2) => pointerCommand("simulator.pointer.controller." + tupledArg_2[0], "Set controller " + tupledArg_2[1], "Simulator controllers", TacticalModality.Simulate), ofArray([["manual", "Manual"], ["scripted", "Scripted AI"], ["general", "General AI"]])), append(selectionActions_1, append(cons(pointerCommand("simulator.pointer.script.set", "Set selected unit direction script", "Simulator controllers", TacticalModality.Simulate), controllerActions), map_1((tupledArg_3) => pointerCommand("simulator.pointer.movement." + tupledArg_3[0], "Move selected unit " + tupledArg_3[1], "Simulator movement", TacticalModality.Simulate), ofArray([["north-west", "NW"], ["north", "N"], ["north-east", "NE"], ["west", "W"], ["east", "E"], ["south-west", "SW"], ["south", "S"], ["south-east", "SE"]]))))))) : ((matchValue_2.tag === 3) ? toList(delay(() => {
        let option_4;
        return append_1(map_1((unit_1) => pointerCommand("review.scene.select.unit." + int32ToString(unit_1.Id), "Select disclosed unit " + int32ToString(unit_1.Id), "Review shared scene", TacticalModality.Review), defaultArg((option_4 = model.Shell.Inspection, (option_4 != null) ? option_4.Units : undefined), empty())), delay(() => {
            let option_7;
            return map_1((event) => pointerCommand("review.scene.select.event." + int32ToString(event.Id), "Select disclosed event " + int32ToString(event.Id), "Review shared scene", TacticalModality.Review), defaultArg((option_7 = model.Shell.Inspection, (option_7 != null) ? option_7.Events : undefined), empty()));
        }));
    })) : toList(delay(() => append_1(singleton_2(pointerCommand("editor.scene.create-simulator-handoff", "Inspect maintained simulation for authored revision", "Editor shared scene", TacticalModality.Editor)), delay(() => append_1(map_1((tupledArg) => {
        const unitId = tupledArg[0] | 0;
        return pointerCommand("editor.scene.select.unit." + int32ToString(unitId), "Select shared-scene unit " + int32ToString(unitId), "Editor shared scene", TacticalModality.Editor);
    }, toList_1(model.Editor.Map.Units)), delay(() => collect((row) => map_2((column) => pointerCommand((("editor.scene.cell." + int32ToString(column)) + ".") + int32ToString(row), (("Activate shared-scene cell " + int32ToString(column)) + ",") + int32ToString(row), "Editor shared scene", TacticalModality.Editor), rangeDouble(0, 1, model.Editor.Map.Width - 1)), rangeDouble(0, 1, model.Editor.Map.Height - 1)))))))))))), append(ofArray([pointerCommand("scene.camera.zoom-out", "Zoom shared workscreen out", "Shared camera", model.Tactical.Modality), pointerCommand("scene.camera.zoom-in", "Zoom shared workscreen in", "Shared camera", model.Tactical.Modality), pointerCommand("scene.camera.fit", "Fit shared workscreen", "Shared camera", model.Tactical.Modality)]), singleton_1(pointerCommand("panel.data", "Rules data", "View", model.Tactical.Modality)))))), {
        Equals: (x_2, y_2) => (x_2 === y_2),
        GetHashCode: (x_2) => (stringHash(x_2) | 0),
    });
}

